"""Deterministic SCHEDULE build-request intake for the tNavigator 22.2 slice.

The same Code-node runtime is embedded in the standalone Intake workflow and
the concrete Builder.  It canonicalizes the trusted specialist handoff, then
fails closed before any model call when temporal policy, units,
mode/preservation intent, or expert RAG binding is incomplete.
"""
from __future__ import annotations

import json


def build_schedule_intake_js(keywords: list[str]) -> str:
    allowed = json.dumps(keywords, ensure_ascii=False)
    return r"""
const raw=$json.schedule_intake_request??$json,obj=v=>v&&typeof v==='object'&&!Array.isArray(v),arr=Array.isArray,clean=v=>typeof v==='string'?v.trim():'';
const x=obj(raw)?raw:{},allowed=new Set(__KEYWORDS__),sha=/^sha256:[a-f0-9]{64}$/i,iso=/^\d{4}-\d{2}-\d{2}$/;
const findings=[],add=(code,severity='error',details={})=>findings.push({code,severity,...details}),validDate=value=>{const s=clean(value);if(!iso.test(s))return false;const d=new Date(`${s}T00:00:00Z`);return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s};
const profile=obj(x.simulator_profile)?x.simulator_profile:{},refs=arr(x.source_artifact_refs)?x.source_artifact_refs:(arr(x.artifact_refs)?x.artifact_refs:[]),scope=arr(x.requested_keyword_scope)?[...new Set(x.requested_keyword_scope.map(v=>clean(v).toUpperCase()).filter(Boolean))]:[];
const inlineBaseline=typeof x.baseline_schedule_text==='string'&&x.baseline_schedule_text.length>0,baselinePresent=inlineBaseline,modeRaw=clean(x.build_mode||'AUTO').toUpperCase(),mode=modeRaw==='AUTO'?(baselinePresent?'REVISE':'CREATE'):modeRaw;
const rag=obj(x.rag_evidence)?x.rag_evidence:{},catalogue=obj(rag.schema_catalogue)?rag.schema_catalogue:(obj(x.schema_catalogue)?x.schema_catalogue:{}),citations=arr(rag.citations)?rag.citations:[];
const policy=obj(x.stage_gate_policy)?x.stage_gate_policy:{attention_threshold:85,hitl_threshold:70,hard_blockers:[]},historyStart=clean(x.history_start),historyEnd=clean(x.history_end),forecastStart=clean(x.forecast_start),forecastEnd=clean(x.forecast_end),modelStart=clean(x.model_start_date);
if(x.contract!=='schedule_build_request'||x.contract_version!=='1.0')add('SCHEDULE_BUILD_CONTRACT_INVALID');
if(!clean(x.task_id)||!clean(x.trace_id)||!clean(x.idempotency_key)||!clean(x.policy_version))add('SCHEDULE_BUILD_IDENTITY_REQUIRED');
if(clean(x.orchestrator_task_id)&&clean(x.task_id)!==clean(x.orchestrator_task_id))add('SCHEDULE_BUILD_TASK_MISMATCH');
if(!Number.isInteger(Number(x.expected_version))||Number(x.expected_version)<0)add('SCHEDULE_BUILD_EXPECTED_VERSION_INVALID');
if(clean(x.policy_version)!=='petroleum-schedule-policy-v1')add('SCHEDULE_POLICY_VERSION_NOT_APPROVED','error',{policy_version:clean(x.policy_version)});
if(!['CREATE','REVISE'].includes(mode))add('INVALID_BUILD_MODE');
if(modeRaw==='CREATE'&&baselinePresent)add('CREATE_BASELINE_CONFLICT_REQUIRES_DECISION','decision',{message:'A baseline is attached while CREATE was requested; choose CREATE and explicitly discard it, or use REVISE.'});
if(mode==='REVISE'&&!baselinePresent)add('BASELINE_REQUIRED');
if(mode==='REVISE'&&clean(x.preservation_policy)!=='preserve_unmentioned')add('PRESERVATION_POLICY_REQUIRED');
if(clean(profile.vendor)!=='Rock Flow Dynamics'||clean(profile.simulator).toLowerCase()!=='tnavigator'||clean(profile.version)!=='22.2')add('SIMULATOR_PROFILE_NOT_APPROVED');
if(clean(profile.unit_system).toUpperCase()!=='METRIC')add('METRIC_UNIT_SYSTEM_REQUIRED');
if(!validDate(modelStart))add('MODEL_START_DATE_REQUIRED');if(!validDate(forecastStart))add('FORECAST_START_DATE_REQUIRED');if(!validDate(forecastEnd))add('FORECAST_END_DATE_REQUIRED');
if(validDate(forecastStart)&&validDate(forecastEnd)&&forecastEnd<forecastStart)add('FORECAST_HORIZON_INVALID');if(validDate(modelStart)&&validDate(forecastStart)&&forecastStart<modelStart)add('FORECAST_BEFORE_MODEL_START');
if(Boolean(historyStart)!==Boolean(historyEnd))add('HISTORY_INTERVAL_INCOMPLETE');if(historyStart&&(!validDate(historyStart)||!validDate(historyEnd)))add('HISTORY_INTERVAL_INVALID');if(validDate(historyStart)&&validDate(historyEnd)&&historyEnd<historyStart)add('HISTORY_INTERVAL_INVALID');if(validDate(modelStart)&&validDate(historyStart)&&historyStart<modelStart)add('HISTORY_BEFORE_MODEL_START');if(validDate(historyEnd)&&validDate(forecastStart)&&forecastStart<historyEnd)add('HISTORY_FORECAST_OVERLAP');
if(scope.includes('WCONHIST')&&(!validDate(historyStart)||!validDate(historyEnd)))add('HISTORY_SCOPE_REQUIRES_INTERVAL');
if(!scope.length)add('KEYWORD_SCOPE_UNRESOLVED');const unsupported=scope.filter(k=>!allowed.has(k));if(unsupported.length)add('UNSUPPORTED_KEYWORD','error',{keywords:unsupported});
const capabilities=arr(x.requested_capability_scope)?x.requested_capability_scope.map(clean).filter(Boolean):[],outputs=arr(x.required_outputs)?x.required_outputs.filter(v=>typeof v==='string'?clean(v):obj(v)):[];
if(mode==='CREATE'&&!capabilities.length)add('CREATE_CAPABILITY_SCOPE_REQUIRED');if(mode==='CREATE'&&!outputs.length)add('CREATE_REQUIRED_OUTPUTS_REQUIRED');
if(mode==='REVISE'&&!obj(x.requested_change_scope))add('REVISE_CHANGE_SCOPE_REQUIRED');
if(!clean(x.objective||x.task?.objective||x.problem_statement))add('OBJECTIVE_REQUIRED');if(!arr(x.acceptance_criteria)||!x.acceptance_criteria.length)add('ACCEPTANCE_CRITERIA_REQUIRED');
if(Number(policy.attention_threshold)!==85||Number(policy.hitl_threshold)!==70||!arr(policy.hard_blockers))add('STAGE_GATE_POLICY_INVALID');
if(!refs.every(r=>obj(r)&&clean(r.ref)&&clean(r.kind)&&clean(r.revision||r.manifest_hash)&&clean(r.description)))add('SOURCE_ARTIFACT_REF_INVALID');if(refs.length>100)add('SOURCE_ARTIFACT_LIMIT','error',{count:refs.length,max:100});
const catalogueProfile=obj(catalogue.simulator_profile)?catalogue.simulator_profile:{},ragAccess=clean(rag.filters?.access_scope),ragBase=clean(rag.filters?.target_base),catalogueSourceHash=clean(catalogue.source_hash).toLowerCase();if(rag.contract!=='schedule_rag_evidence'||rag.contract_version!=='1.0'||!citations.length||!ragAccess||ragBase!=='schedule_mvp'||catalogue.contract!=='schedule_schema_catalogue'||catalogue.contract_version!=='1.0'||!clean(catalogue.approved_by||catalogue.author)||!sha.test(clean(catalogue.catalogue_hash))||!sha.test(catalogueSourceHash)||clean(catalogueProfile.simulator).toLowerCase()!=='tnavigator'||clean(catalogueProfile.version)!=='22.2')add('EXPERT_KNOWLEDGE_AND_CATALOGUE_BINDING_REQUIRED');
const covered=new Set(citations.filter(c=>clean(c.knowledge_type)==='keyword_instruction').flatMap(c=>{const raw=c?.keyword_families??c?.keywords??[];return arr(raw)?raw.map(v=>clean(v).toUpperCase()):[]}));const missingCitationScope=scope.filter(k=>!covered.has(k));if(missingCitationScope.length)add('KEYWORD_INSTRUCTION_SCOPE_INCOMPLETE','error',{keywords:missingCitationScope});
if(citations.some(c=>!obj(c)||!clean(c.knowledge_id)||!clean(c.revision)||!clean(c.content_hash)||!clean(c.author)||!clean(c.knowledge_type)))add('EXPERT_KNOWLEDGE_CITATION_INVALID');
const maxRequestBytes=inlineBaseline?2359296:524288;let requestBytes=Number.MAX_SAFE_INTEGER;try{requestBytes=new TextEncoder().encode(JSON.stringify(x)).length}catch{}if(requestBytes>maxRequestBytes)add('SCHEDULE_BUILD_REQUEST_TOO_LARGE','error',{byte_length:requestBytes,max_bytes:maxRequestBytes});
const hard=findings.filter(f=>f.severity==='error'),decisionFindings=findings.filter(f=>f.severity==='decision'),status=decisionFindings.length?'needs_decision':hard.length?'needs_input':'accepted';
const questions=findings.slice(0,100).map((f,index)=>({id:`intake_${index+1}_${String(f.code).toLowerCase()}`,code:f.code,question:({SCHEDULE_BUILD_CONTRACT_INVALID:'Use the governed schedule_build_request/v1 handoff.',SCHEDULE_BUILD_IDENTITY_REQUIRED:'Provide task/trace/idempotency/policy identity for this build.',SCHEDULE_BUILD_TASK_MISMATCH:'Restart from the current orchestrator task; do not reuse a packet from another task.',SCHEDULE_BUILD_EXPECTED_VERSION_INVALID:'Provide the current non-negative orchestrator task version.',SCHEDULE_POLICY_VERSION_NOT_APPROVED:'Use petroleum-schedule-policy-v1 or obtain a compatibility approval.',CREATE_BASELINE_CONFLICT_REQUIRES_DECISION:'Confirm whether to preserve and revise the attached baseline or explicitly discard it and create a new Schedule.',BASELINE_REQUIRED:'Attach the previous SCHEDULE text for REVISE.',PRESERVATION_POLICY_REQUIRED:'Set preservation_policy to preserve_unmentioned.',SIMULATOR_PROFILE_NOT_APPROVED:'Select the tNavigator 22.2 compatibility profile.',METRIC_UNIT_SYSTEM_REQUIRED:'Confirm simulator_profile.unit_system = METRIC.',MODEL_START_DATE_REQUIRED:'Provide model_start_date as YYYY-MM-DD.',FORECAST_START_DATE_REQUIRED:'Provide forecast_start as an approved YYYY-MM-DD cutover.',FORECAST_END_DATE_REQUIRED:'Provide forecast_end as YYYY-MM-DD.',KEYWORD_SCOPE_UNRESOLVED:'Select the required SCHEDULE keyword scope.',CREATE_CAPABILITY_SCOPE_REQUIRED:'List requested capabilities for CREATE.',CREATE_REQUIRED_OUTPUTS_REQUIRED:'List measurable required outputs for CREATE.',REVISE_CHANGE_SCOPE_REQUIRED:'Provide requested_change_scope for REVISE.',OBJECTIVE_REQUIRED:'Provide the engineering objective.',ACCEPTANCE_CRITERIA_REQUIRED:'Provide measurable acceptance criteria.',EXPERT_KNOWLEDGE_AND_CATALOGUE_BINDING_REQUIRED:'Load active expert keyword instructions and a matching machine-readable schema catalogue in schedule_mvp.',KEYWORD_INSTRUCTION_SCOPE_INCOMPLETE:'Load one complete active keyword_instruction for every requested keyword.'}[f.code]||f.message||`Resolve intake finding ${f.code}.`),expected_format:f.code.includes('DATE')||f.code.includes('HORIZON')||f.code.includes('INTERVAL')?'YYYY-MM-DD or bounded interval':'governed value/reference with provenance',required:true}));
const components={identity:(!findings.some(f=>/CONTRACT|IDENTITY|TASK_MISMATCH|EXPECTED_VERSION|POLICY_VERSION/.test(f.code)))?100:0,profile_and_units:(!findings.some(f=>/PROFILE|UNIT_SYSTEM/.test(f.code)))?100:0,temporal_scope:(!findings.some(f=>/DATE|HISTORY|FORECAST|HORIZON/.test(f.code)))?100:0,evidence_and_scope:(!findings.some(f=>/KEYWORD|CAPABILITY|OUTPUTS|CHANGE_SCOPE|KNOWLEDGE|CATALOGUE|RAG/.test(f.code)))?100:0};const stageScore=Math.round(.20*components.identity+.25*components.profile_and_units+.25*components.temporal_scope+.30*components.evidence_and_scope),gate=hard.length||decisionFindings.length||stageScore<70?'hitl':stageScore<85?'attention':'continue';
return[{json:{contract:'schedule_intake_result',contract_version:'1.0',status,build_mode:mode,objective:clean(x.objective||x.task?.objective||x.problem_statement),task_id:clean(x.task_id),trace_id:clean(x.trace_id),idempotency_key:clean(x.idempotency_key),policy_version:clean(x.policy_version),expected_version:Number.isInteger(Number(x.expected_version))?Number(x.expected_version):null,simulator_profile:{vendor:'Rock Flow Dynamics',simulator:'tNavigator',version:'22.2',unit_system:clean(profile.unit_system).toUpperCase()},baseline_present:baselinePresent,baseline_manifest_hash:clean(x.baseline_manifest_hash||x.baseline_source_hash).toLowerCase()||null,model_start_date:modelStart||null,history_start:historyStart||null,history_end:historyEnd||null,forecast_start:forecastStart||null,forecast_end:forecastEnd||null,requested_keyword_scope:scope,requested_capability_scope:capabilities,required_outputs:outputs,requested_change_scope:obj(x.requested_change_scope)?x.requested_change_scope:{},preservation_policy:mode==='REVISE'?'preserve_unmentioned':'not_applicable',source_artifact_refs:refs,knowledge_binding:{target_base:ragBase,knowledge_ids:[...new Set(citations.map(c=>clean(c.knowledge_id)).filter(Boolean))],content_hashes:[...new Set(citations.map(c=>clean(c.content_hash)).filter(Boolean))],catalogue_hash:clean(catalogue.catalogue_hash).toLowerCase()||null},stage_gate_policy:{attention_threshold:85,hitl_threshold:70,hard_blockers:arr(policy.hard_blockers)?policy.hard_blockers.slice(0,100):[]},findings,hard_blockers:hard.map(f=>f.code),questions,score:{stage_score:stageScore,components,raw_counts:{findings:findings.length,hard_blockers:hard.length,decision_findings:decisionFindings.length,requested_keywords:scope.length,capabilities:capabilities.length,required_outputs:outputs.length,citations:citations.length,source_artifacts:refs.length},thresholds:{attention:85,hitl:70},decision:gate,provisional:false},next_action:status==='accepted'?'plan':status==='needs_decision'?'ask_human_decision':'ask_human_input'}}];
""".replace("__KEYWORDS__", allowed).strip()
