"""Catalogue-driven decoder for lossless SCHEDULE baseline packages.

The decoder never embeds vendor field layouts. It expands the already-vetted
INCLUDE graph in execution order, tokenizes records losslessly enough to bind
them back to CST nodes, resolves exactly one approved schema variant, and
emits typed IR split at an explicit change boundary.
"""
from __future__ import annotations

import json

from schedule_lossless_runtime import SHA256_JS


def build_baseline_decoder_js(keywords: list[str]) -> str:
    allowed = json.dumps(keywords, ensure_ascii=False)
    return r"""
const x=$json.baseline_decode_request??$json;
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),arr=Array.isArray,clean=v=>typeof v==='string'?v.trim():'';
const allowed=new Set(__KEYWORDS__),findings=[];
__SHA256_JS__
const hash=contentHash,shaPattern=/^sha256:[a-f0-9]{64}$/i,analysis=obj(x.baseline_analysis)?x.baseline_analysis:{};
const pkg=obj(analysis.package)?analysis.package:(obj(x.package)?x.package:{}),catalogue=obj(x.schema_catalogue)?x.schema_catalogue:{};
const schemas=arr(catalogue.schemas)?catalogue.schemas.filter(obj):[],schemaMap=new Map(),nonRecord=new Set(arr(catalogue.non_record_keywords)?catalogue.non_record_keywords.map(v=>clean(v).toUpperCase()).filter(Boolean):[]);
const profile=obj(catalogue.simulator_profile)?catalogue.simulator_profile:{},sourceHash=clean(catalogue.source_hash).toLowerCase(),catalogueHash=clean(catalogue.catalogue_hash).toLowerCase();
const changeBoundary=clean(x.change_effective_from),modelStart=clean(x.model_start_date),initial=obj(x.initial_semantic_snapshot)?x.initial_semantic_snapshot:{};
const MAX_RECORDS=50000,MAX_TOKENS=1000000,MAX_EXPANSION=1000;
if(analysis.contract!=='baseline_analysis'||analysis.contract_version!=='1.0'||analysis.status!=='analyzed'||!obj(pkg)||!arr(pkg.files)||!clean(pkg.package_hash))findings.push({code:'BASELINE_ANALYSIS_REQUIRED',severity:'error'});
if(catalogue.contract!=='schedule_schema_catalogue'||catalogue.contract_version!=='1.0')findings.push({code:'SCHEMA_CATALOGUE_CONTRACT_INVALID',severity:'error'});
if(clean(profile.vendor)!=='Rock Flow Dynamics'||clean(profile.simulator).toLowerCase()!=='tnavigator'||clean(profile.version)!=='22.2')findings.push({code:'SCHEMA_PROFILE_NOT_APPROVED',severity:'error'});
if(catalogue.approved!==true||!clean(catalogue.approved_by)||!clean(catalogue.approval_gate_id||catalogue.approval_gate||'catalogue-approved'))findings.push({code:'SCHEMA_ACCOUNTABLE_APPROVAL_REQUIRED',severity:'error'});
if(!shaPattern.test(sourceHash)||!shaPattern.test(catalogueHash))findings.push({code:'SCHEMA_HASH_INVALID',severity:'error'});
if(!schemas.length)findings.push({code:'SCHEMA_CATALOGUE_EMPTY',severity:'error'});
for(const kw of nonRecord)if(!['SCHEDULE'].includes(kw))findings.push({code:'NON_RECORD_KEYWORD_NOT_ALLOWED',severity:'error',keyword:kw});
const month={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};
const parseDate=raw=>{const t=clean(raw).toUpperCase();let m=t.match(/^(\d{4})-(\d{2})-(\d{2})$/),y,mo,d;if(m){y=Number(m[1]);mo=Number(m[2])-1;d=Number(m[3])}else{m=t.match(/^(\d{1,2})\s+([A-Z]{3})\s+(\d{4})$/);if(!m||month[m[2]]===undefined)return null;d=Number(m[1]);mo=month[m[2]];y=Number(m[3])}const epoch=Date.UTC(y,mo,d),v=new Date(epoch);return v.getUTCFullYear()===y&&v.getUTCMonth()===mo&&v.getUTCDate()===d?{iso:`${String(y).padStart(4,'0')}-${String(mo+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,epoch}:null};
const boundaryDate=parseDate(changeBoundary),startDate=parseDate(modelStart);
if(!boundaryDate)findings.push({code:'CHANGE_EFFECTIVE_FROM_REQUIRED',severity:'error'});
if(!startDate)findings.push({code:'MODEL_START_DATE_REQUIRED',severity:'error'});
if(boundaryDate&&startDate&&boundaryDate.epoch<=startDate.epoch)findings.push({code:'CHANGE_BOUNDARY_NOT_AFTER_MODEL_START',severity:'error'});
const changeKeywords=new Set((arr(x.requested_keyword_scope)?x.requested_keyword_scope:[]).map(v=>clean(v).toUpperCase()).filter(Boolean));
const names=s=>new Set((arr(s.fields)?s.fields:[]).map(f=>clean(f?.name)).filter(Boolean));
for(let i=0;i<schemas.length;i++){
  const s=schemas[i],kw=clean(s.keyword).toUpperCase(),variant=clean(s.variant)||'default',fields=arr(s.fields)?s.fields.filter(obj):[],sem=obj(s.semantics)?s.semantics:null,key=`${kw}::${variant}`;
  if(!allowed.has(kw)||!clean(s.schema_id)||!clean(s.schema_revision)||!fields.length||!sem){findings.push({code:'BASELINE_SCHEMA_INVALID',severity:'error',keyword:kw,variant,index:i});continue}
  const positions=fields.map(f=>Number(f.position));if(positions.some((p,j)=>!Number.isInteger(p)||p!==j+1)){findings.push({code:'BASELINE_SCHEMA_FIELDS_INVALID',severity:'error',keyword:kw,variant});continue}
  if(schemaMap.has(kw)&&schemaMap.get(kw).some(v=>v.variant===variant)){findings.push({code:'BASELINE_SCHEMA_VARIANT_DUPLICATE',severity:'error',keyword:kw,variant});continue}
  const n=names(s),clock=obj(sem.clock)?sem.clock:{};for(const f of [clock.sets_from_field,clock.effective_date_field].filter(Boolean))if(!n.has(clean(f)))findings.push({code:'SEMANTIC_FIELD_UNKNOWN',severity:'error',keyword:kw,variant,field:f});
  if(!clean(clock.sets_from_field)&&!clean(clock.effective_date_field)&&clock.uses_current!==true){findings.push({code:'BASELINE_CLOCK_POLICY_REQUIRED',severity:'error',keyword:kw,variant});continue}
  schemaMap.set(kw,[...(schemaMap.get(kw)||[]),{...s,keyword:kw,variant,fields:fields.slice().sort((a,b)=>Number(a.position)-Number(b.position)),semantics:sem}]);
}
const stripHeader=raw=>{const t=String(raw),m=t.match(/^(?:\ufeff)?[^\r\n]*(?:\r\n|\n|\r)?/);return t.slice(m?m[0].length:0)};
const tokenizeRecords=(raw,node)=>{const body=stripHeader(raw),records=[],tokens=[];let token='',quoted=false,wasQuoted=false,inComment=false,recordStart=0,tokenCount=0;
  const push=()=>{if(token.length||wasQuoted){tokens.push({raw:token,quoted:wasQuoted});token='';wasQuoted=false;tokenCount++;if(tokenCount>MAX_TOKENS)findings.push({code:'BASELINE_TOKEN_LIMIT',severity:'error',node_id:node.node_id})}};
  const finish=pos=>{push();if(tokens.length){records.push({tokens:tokens.splice(0),record_index:records.length,body_end:pos});if(records.length>MAX_RECORDS)findings.push({code:'BASELINE_RECORD_LIMIT',severity:'error',node_id:node.node_id})}recordStart=pos+1};
  for(let i=0;i<body.length;i++){const ch=body[i],next=body[i+1];if(inComment){if(ch==='\r'||ch==='\n')inComment=false;continue}if(quoted){if(ch==="'"&&next==="'"){token+="'";i++;continue}if(ch==="'"){quoted=false;wasQuoted=true;continue}token+=ch;continue}if(ch==='-'&&next==='-'){push();inComment=true;i++;continue}if(ch==="'"){if(token.length){findings.push({code:'BASELINE_QUOTE_POSITION_INVALID',severity:'error',node_id:node.node_id});return[]}quoted=true;continue}if(ch==='/'){finish(i);continue}if(/[\s,]/.test(ch)){push();continue}token+=ch}
  if(quoted)findings.push({code:'BASELINE_QUOTE_UNTERMINATED',severity:'error',node_id:node.node_id});push();if(tokens.length)findings.push({code:'BASELINE_RECORD_UNTERMINATED',severity:'error',node_id:node.node_id,record_start:recordStart});return records};
const expandTokens=(tokens,node,recordIndex)=>{const out=[];for(const tok of tokens){if(!tok.quoted){const m=tok.raw.match(/^(\d+)\*(.*)$/);if(m){const count=Number(m[1]),suffix=m[2];if(!Number.isInteger(count)||count<1||count>MAX_EXPANSION){findings.push({code:'BASELINE_REPEAT_LIMIT',severity:'error',node_id:node.node_id,record_index:recordIndex});return[]}for(let i=0;i<count;i++)out.push(suffix?{raw:suffix,quoted:false}:{raw:'*',quoted:false,defaulted:true});continue}if(tok.raw==='*'){out.push({...tok,defaulted:true});continue}}out.push(tok)}return out};
const fieldWidth=f=>{const explicit=Number(f.parse_token_width??f.parser?.token_width);if(Number.isInteger(explicit)&&explicit>0)return explicit;if(clean(f.type).toLowerCase()==='date'&&clean(f.format).toUpperCase()==='DD MON YYYY')return 3;return 1};
const parseScalar=(slice,f,parser)=>{if(slice.length!==fieldWidth(f))return{ok:false,reason:'TOKEN_WIDTH'};if(slice.length===1&&slice[0].defaulted){if(f.default_allowed!==true)return{ok:false,reason:'DEFAULT_NOT_ALLOWED'};return{ok:true,value:{state:'default'}}}const raw=slice.map(t=>t.raw).join(' '),type=clean(f.type).toLowerCase();if(type==='string'){if((f.quote==='single'||f.quote==='SINGLE')&&!slice.every(t=>t.quoted)&&parser.allow_unquoted_strings!==true)return{ok:false,reason:'QUOTE_REQUIRED'};if(!raw||/[\r\n\0]/.test(raw))return{ok:false,reason:'STRING_INVALID'};return{ok:true,value:raw}}if(type==='integer'){if(!/^[-+]?\d+$/.test(raw))return{ok:false,reason:'INTEGER_INVALID'};const n=Number(raw);return Number.isSafeInteger(n)?{ok:true,value:n}:{ok:false,reason:'INTEGER_RANGE'}}if(type==='number'){if(!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?$/.test(raw))return{ok:false,reason:'NUMBER_INVALID'};const n=Number(raw);return Number.isFinite(n)?{ok:true,value:n}:{ok:false,reason:'NUMBER_RANGE'}}if(type==='date'){const d=parseDate(raw);return d?{ok:true,value:d.iso}:{ok:false,reason:'DATE_INVALID'}}if(type==='enum'){const values=arr(f.enum)?f.enum.map(String):[],hit=values.find(v=>v.toUpperCase()===raw.toUpperCase());return hit===undefined?{ok:false,reason:'ENUM_INVALID'}:{ok:true,value:hit}}if(type==='boolean'){const yes=clean(f.true_token)||'YES',no=clean(f.false_token)||'NO';if(raw.toUpperCase()===yes.toUpperCase())return{ok:true,value:true};if(raw.toUpperCase()===no.toUpperCase())return{ok:true,value:false};return{ok:false,reason:'BOOLEAN_INVALID'}}return{ok:false,reason:'TYPE_UNSUPPORTED'}};
const decodeVariant=(tokens,schema)=>{const parser=obj(schema.parser)?schema.parser:{},fields={},errors=[],totalWidth=Number(parser.token_width);if(Number.isInteger(totalWidth)&&totalWidth>0){if(tokens.length>totalWidth)errors.push({reason:'VARIANT_TOKEN_WIDTH_MISMATCH',expected:totalWidth,actual:tokens.length});else if(tokens.length<totalWidth&&parser.allow_trailing_omission!==true)errors.push({reason:'VARIANT_TOKEN_WIDTH_MISMATCH',expected:totalWidth,actual:tokens.length})}let at=0;for(const f of schema.fields){const width=fieldWidth(f);if(at+width>tokens.length){if(parser.allow_trailing_omission===true&&f.required!==true&&f.default_allowed===true){fields[clean(f.name)]={state:'default'};continue}errors.push({field:clean(f.name),reason:'FIELD_MISSING'});continue}const decoded=parseScalar(tokens.slice(at,at+width),f,parser);if(!decoded.ok){errors.push({field:clean(f.name),reason:decoded.reason});at+=width;continue}fields[clean(f.name)]=decoded.value;at+=width}if(at<tokens.length){const withinWidth=Number.isInteger(totalWidth)&&totalWidth>0&&tokens.length<=totalWidth;if(!(withinWidth&&parser.allow_trailing_omission===true))errors.push({reason:'EXTRA_TOKENS',count:tokens.length-at})}const match=obj(parser.match)?parser.match:{};for(const [name,expected] of Object.entries(match)){const actual=fields[name],values=arr(expected)?expected:[expected];if(!values.some(v=>String(v).toUpperCase()===String(actual).toUpperCase()))errors.push({field:name,reason:'VARIANT_SELECTOR_MISMATCH'})}return{ok:errors.length===0,fields,errors}};
const decodeRecord=(kw,tokens,node,recordIndex)=>{const variants=schemaMap.get(kw)||[],candidates=[];if(!variants.length){findings.push({code:'BASELINE_SCHEMA_NOT_BOUND_KEPT',severity:changeKeywords.has(kw)?'error':'warning',node_id:node.node_id,keyword:kw,record_index:recordIndex});return null}for(const s of variants){const r=decodeVariant(tokens,s);if(r.ok)candidates.push({schema:s,fields:r.fields})}if(!candidates.length){findings.push({code:'BASELINE_RECORD_SCHEMA_MISMATCH',severity:'warning',node_id:node.node_id,keyword:kw,record_index:recordIndex,token_count:tokens.length,note:'Keep raw baseline record; bound catalogue variant did not parse this row'});return null}if(candidates.length===1)return candidates[0];
  const scored=candidates.map(c=>{let score=0;const schema=c.schema,fields=c.fields,parser=obj(schema.parser)?schema.parser:{},totalWidth=Number(parser.token_width);
    if(Number.isInteger(totalWidth)&&totalWidth>0&&totalWidth===tokens.length)score+=100;
    for(const f of(arr(schema.fields)?schema.fields:[])){const enums=arr(f.enum)?f.enum.map(String):[];if(!enums.length)continue;const val=fields[clean(f.name)];if(val!=null&&typeof val!=='object'&&enums.some(e=>e.toUpperCase()===String(val).toUpperCase()))score+=50;else if(val!=null&&typeof val!=='object')score-=25}
    score-=Object.values(fields).filter(v=>v&&typeof v==='object'&&v.state==='default').length;
    const variant=clean(schema.variant).toUpperCase(),control=String(fields.CONTROL??'').toUpperCase();if(variant&&control&&variant===control)score+=80;
    return{...c,score}});
  scored.sort((a,b)=>b.score-a.score);
  if(scored.length>=2&&scored[0].score>scored[1].score)return{schema:scored[0].schema,fields:scored[0].fields};
  findings.push({code:'BASELINE_RECORD_VARIANT_AMBIGUOUS',severity:'error',node_id:node.node_id,keyword:kw,record_index:recordIndex,variants:candidates.map(c=>c.schema.variant),scores:scored.map(c=>({variant:c.schema.variant,score:c.score}))});return null};
const files=arr(pkg.files)?pkg.files.filter(obj):[],byFile=new Map(files.map(f=>[clean(f.file_ref),f])),graph=obj(analysis.include_graph)?analysis.include_graph:{};
const decoded=[],expanded=new Set();let sequence=0,current=startDate;
const append=(node,record,hit)=>{const sem=hit.schema.semantics,clock=obj(sem.clock)?sem.clock:{},fields=hit.fields;let effective=null;if(clean(clock.sets_from_field)){effective=parseDate(fields[clean(clock.sets_from_field)]);if(!effective)findings.push({code:'BASELINE_CLOCK_VALUE_INVALID',severity:'error',node_id:node.node_id,field:clock.sets_from_field});else{if(current&&effective.epoch<=current.epoch)findings.push({code:'BASELINE_CLOCK_NOT_STRICTLY_INCREASING',severity:'error',node_id:node.node_id,previous:current.iso,current:effective.iso});current=effective}}else if(clean(clock.effective_date_field)){effective=parseDate(fields[clean(clock.effective_date_field)]);if(!effective)findings.push({code:'BASELINE_EFFECTIVE_DATE_INVALID',severity:'error',node_id:node.node_id,field:clock.effective_date_field})}else if(clock.uses_current===true)effective=current;if(!effective)findings.push({code:'BASELINE_EFFECTIVE_DATE_REQUIRED',severity:'error',node_id:node.node_id,keyword:node.keyword});const recordHash=hash(JSON.stringify({keyword:node.keyword,variant:hit.schema.variant,fields}));decoded.push({event_id:`baseline:${hash(`${node.node_id}|${record.record_index}|${recordHash}`).slice(7,31)}`,operation:'ADD',keyword:node.keyword,variant:hit.schema.variant,fields,effective_at:effective?.iso||null,source_node_id:node.node_id,target_node_id:node.node_id,expected_raw_hash:node.raw_hash,file_ref:node.file_ref||null,record_index:record.record_index,execution_sequence:sequence++,record_hash:recordHash,schema_id:hit.schema.schema_id,schema_revision:hit.schema.schema_revision,provenance:[{source_ref:`baseline://${node.node_id}#record=${record.record_index}`,raw_hash:node.raw_hash}]})};
const visit=(fileRef,stack)=>{if(stack.includes(fileRef)){findings.push({code:'INCLUDE_CYCLE',severity:'error',cycle:[...stack,fileRef]});return}if(expanded.has(fileRef)){findings.push({code:'INCLUDE_MULTIPLE_EXPANSION',severity:'error',file_ref:fileRef});return}const file=byFile.get(fileRef);if(!file){findings.push({code:'INCLUDE_NOT_FOUND',severity:'error',file_ref:stack[stack.length-1]||fileRef,path:fileRef,target_file_ref:fileRef});return}expanded.add(fileRef);for(const rawNode of(arr(file.nodes)?file.nodes:[])){const node={...rawNode,file_ref:fileRef},kw=clean(node.keyword).toUpperCase();if(node.kind==='trivia'||!kw)continue;if(node.opaque||node.known===false){if(nonRecord.has(kw))continue;findings.push({code:'OPAQUE_BASELINE_SEMANTICS_UNAVAILABLE',severity:changeKeywords.has(kw)?'error':'warning',file_ref:fileRef,node_id:node.node_id,keyword:kw,note:changeKeywords.has(kw)?'Targeted opaque keyword needs schema before mutation':'Untouched opaque keyword kept byte-for-byte'});continue}if(kw==='INCLUDE'){const records=tokenizeRecords(node.raw,node),edges=arr(graph[fileRef])?graph[fileRef].filter(e=>clean(e.source_node_id)===clean(node.node_id)):[];if(records.length!==1||records[0].tokens.length!==1||records[0].tokens[0].quoted!==true)findings.push({code:'INCLUDE_RECORD_INVALID',severity:'error',file_ref:fileRef,node_id:node.node_id});if(edges.length!==1)findings.push({code:'INCLUDE_EDGE_AMBIGUOUS',severity:'error',file_ref:fileRef,node_id:node.node_id,count:edges.length});else{const declared=records[0]?.tokens?.[0]?.raw;if(clean(declared)!==clean(edges[0].raw_path))findings.push({code:'INCLUDE_EDGE_PATH_MISMATCH',severity:'error',file_ref:fileRef,node_id:node.node_id,declared,target:edges[0].raw_path});visit(clean(edges[0].target_file_ref),[...stack,fileRef])}continue}const records=tokenizeRecords(node.raw,node);for(const record of records){const tokens=expandTokens(record.tokens,node,record.record_index);if(!tokens.length)continue;const hit=decodeRecord(kw,tokens,node,record.record_index);if(hit)append(node,record,hit)}}};
if(clean(pkg.root_path))visit(clean(pkg.root_path),[]);else findings.push({code:'BASELINE_ROOT_REQUIRED',severity:'error'});
const prefix=boundaryDate?decoded.filter(e=>parseDate(e.effective_at)?.epoch<boundaryDate.epoch):[],suffix=boundaryDate?decoded.filter(e=>parseDate(e.effective_at)?.epoch>=boundaryDate.epoch):decoded.slice();
const compact=e=>({event_id:e.event_id,keyword:e.keyword,variant:e.variant,effective_at:e.effective_at,source_node_id:e.source_node_id,record_index:e.record_index,record_hash:e.record_hash});
const initialBody={...initial};delete initialBody.snapshot_hash;const computedInitialHash=hash(JSON.stringify(initialBody)),declaredInitialHash=clean(initial.snapshot_hash),initialHash=declaredInitialHash||computedInitialHash;if(declaredInitialHash&&declaredInitialHash!==computedInitialHash)findings.push({code:'INITIAL_SEMANTIC_SNAPSHOT_HASH_MISMATCH',severity:'error',expected:declaredInitialHash,actual:computedInitialHash});
const prefixHash=hash(JSON.stringify(prefix.map(compact))),decodedHash=hash(JSON.stringify(decoded.map(compact)));
const hard=findings.filter(f=>f.severity==='error'),counts=decoded.reduce((a,e)=>(a[e.keyword]=(a[e.keyword]||0)+1,a),{}),recordView=e=>({event_id:e.event_id,keyword:e.keyword,variant:e.variant,fields:e.fields,effective_at:e.effective_at,source_node_id:e.source_node_id,target_node_id:e.target_node_id,expected_raw_hash:e.expected_raw_hash,file_ref:e.file_ref,record_index:e.record_index,execution_sequence:e.execution_sequence,record_hash:e.record_hash,schema_id:e.schema_id,schema_revision:e.schema_revision,provenance:e.provenance});
return[{json:{contract:'baseline_decode_result',contract_version:'1.0',status:hard.length?'needs_input':'decoded',baseline_package_hash:clean(pkg.package_hash)||null,catalogue_hash:catalogueHash||null,change_effective_from:boundaryDate?.iso||null,model_start_date:startDate?.iso||null,decoded_ir_events:hard.length?[]:decoded,prefix_ir_events:hard.length?[]:prefix,suffix_ir_events:hard.length?[]:suffix,decoded_records:hard.length?[]:decoded.map(recordView),prefix_records:hard.length?[]:prefix.map(recordView),suffix_records:hard.length?[]:suffix.map(recordView),prefix_hash:prefixHash,decoded_hash:decodedHash,initial_snapshot_hash:initialHash,keyword_counts:counts,execution_files:[...expanded],findings,hard_blockers:[...new Set(hard.map(f=>f.code))],metrics:{files:expanded.size,records:decoded.length,prefix_records:prefix.length,suffix_records:suffix.length}}}];
""".replace("__KEYWORDS__", allowed).replace("__SHA256_JS__", SHA256_JS)
