"""Lossless lexical SCHEDULE runtime used by the n8n 2.30.8 Code nodes.

The parser deliberately stops at a lexical/CST boundary.  It does not pretend
to know tNavigator field order or defaults; those belong to the licensed,
approved 22.2 catalogue.  What it does guarantee is preservation of the
original text, line endings, opaque keyword blocks, and exact mutation targets.
"""
from __future__ import annotations

import json


SHA256_JS = r"""
const SHA_K=[
  0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
];
const shaUtf8=s=>{const out=[],t=String(s);for(let i=0;i<t.length;i++){let cp=t.codePointAt(i);if(cp>0xffff)i++;if(cp>=0xd800&&cp<=0xdfff)cp=0xfffd;if(cp<=0x7f)out.push(cp);else if(cp<=0x7ff)out.push(0xc0|(cp>>6),0x80|(cp&63));else if(cp<=0xffff)out.push(0xe0|(cp>>12),0x80|((cp>>6)&63),0x80|(cp&63));else out.push(0xf0|(cp>>18),0x80|((cp>>12)&63),0x80|((cp>>6)&63),0x80|(cp&63))}return out};
const shaRotr=(v,n)=>(v>>>n)|(v<<(32-n));
const sha256=s=>{const b=shaUtf8(s),bit=b.length*8,b2=b.slice();b2.push(0x80);while((b2.length%64)!==56)b2.push(0);for(let i=7;i>=0;i--)b2.push((bit/Math.pow(2,i*8))&255);let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a,h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19;for(let off=0;off<b2.length;off+=64){const w=new Array(64);for(let i=0;i<16;i++){const p=off+i*4;w[i]=((b2[p]<<24)|(b2[p+1]<<16)|(b2[p+2]<<8)|b2[p+3])>>>0}for(let i=16;i<64;i++){const a=w[i-15],c=w[i-2],s0=(shaRotr(a,7)^shaRotr(a,18)^(a>>>3))>>>0,s1=(shaRotr(c,17)^shaRotr(c,19)^(c>>>10))>>>0;w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let a=h0,bv=h1,c=h2,d=h3,e=h4,f=h5,g=h6,hh=h7;for(let i=0;i<64;i++){const S1=(shaRotr(e,6)^shaRotr(e,11)^shaRotr(e,25))>>>0,ch=((e&f)^((~e)&g))>>>0,t1=(hh+S1+ch+SHA_K[i]+w[i])>>>0,S0=(shaRotr(a,2)^shaRotr(a,13)^shaRotr(a,22))>>>0,maj=((a&bv)^(a&c)^(bv&c))>>>0,t2=(S0+maj)>>>0;hh=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=bv;bv=a;a=(t1+t2)>>>0}h0=(h0+a)>>>0;h1=(h1+bv)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;h5=(h5+f)>>>0;h6=(h6+g)>>>0;h7=(h7+hh)>>>0}return [h0,h1,h2,h3,h4,h5,h6,h7].map(v=>v.toString(16).padStart(8,'0')).join('')};
const contentHash=s=>`sha256:${sha256(String(s??''))}`;
"""


def build_baseline_js(keywords: list[str]) -> str:
    allowed = json.dumps(keywords, ensure_ascii=False)
    return r"""
const x=$json.baseline_request??$json;
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),clean=v=>typeof v==='string'?v.trim():'';
const allowed=new Set(__KEYWORDS__);
const MAX_BYTES=2000000,MAX_FILES=100,MAX_NODES=10000,MAX_DEPTH=32;

// SHA-256 is intentionally implemented in the Code node.  A workflow export
// must not depend on Node's `require` or on a host filesystem helper.
const K=[
  0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
];
const utf8=s=>{const out=[];for(let i=0;i<String(s).length;i++){let cp=String(s).codePointAt(i);if(cp>0xffff)i++;if(cp>=0xd800&&cp<=0xdfff)cp=0xfffd;if(cp<=0x7f)out.push(cp);else if(cp<=0x7ff)out.push(0xc0|(cp>>6),0x80|(cp&63));else if(cp<=0xffff)out.push(0xe0|(cp>>12),0x80|((cp>>6)&63),0x80|(cp&63));else out.push(0xf0|(cp>>18),0x80|((cp>>12)&63),0x80|((cp>>6)&63),0x80|(cp&63))}return out};
const rotr=(v,n)=>(v>>>n)|(v<<(32-n));
const sha256=s=>{const b=utf8(s),bit=b.length*8,b2=b.slice();b2.push(0x80);while((b2.length%64)!==56)b2.push(0);for(let i=7;i>=0;i--)b2.push((bit/Math.pow(2,i*8))&255);let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a,h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19;for(let off=0;off<b2.length;off+=64){const w=new Array(64);for(let i=0;i<16;i++){const p=off+i*4;w[i]=((b2[p]<<24)|(b2[p+1]<<16)|(b2[p+2]<<8)|b2[p+3])>>>0}for(let i=16;i<64;i++){const a=w[i-15],c=w[i-2],s0=(rotr(a,7)^rotr(a,18)^(a>>>3))>>>0,s1=(rotr(c,17)^rotr(c,19)^(c>>>10))>>>0;w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let a=h0,bv=h1,c=h2,d=h3,e=h4,f=h5,g=h6,hh=h7;for(let i=0;i<64;i++){const S1=(rotr(e,6)^rotr(e,11)^rotr(e,25))>>>0,ch=((e&f)^((~e)&g))>>>0,t1=(hh+S1+ch+K[i]+w[i])>>>0,S0=(rotr(a,2)^rotr(a,13)^rotr(a,22))>>>0,maj=((a&bv)^(a&c)^(bv&c))>>>0,t2=(S0+maj)>>>0;hh=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=bv;bv=a;a=(t1+t2)>>>0}h0=(h0+a)>>>0;h1=(h1+bv)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;h5=(h5+f)>>>0;h6=(h6+g)>>>0;h7=(h7+hh)>>>0}return [h0,h1,h2,h3,h4,h5,h6,h7].map(v=>v.toString(16).padStart(8,'0')).join('')};
const hash=s=>`sha256:${sha256(String(s??''))}`;
const utf8Length=s=>utf8(String(s)).length;
const utf8Prefix=s=>{const p=new Array(String(s).length+1);let b=0;p[0]=0;for(let i=0;i<String(s).length;i++){let cp=String(s).codePointAt(i);if(cp>0xffff){b+=4;p[i+1]=b;p[i+2]=b;i++;continue}if(cp>=0xd800&&cp<=0xdfff)cp=0xfffd;b+=cp<=0x7f?1:cp<=0x7ff?2:cp<=0xffff?3:4;p[i+1]=b}return p};
const lineList=s=>{const a=[],t=String(s);let start=0,line=1;for(let i=0;i<t.length;i++){if(t[i]==='\r'||t[i]==='\n'){const e=t[i]==='\r'&&t[i+1]==='\n'?'\r\n':t[i];const end=i+e.length;a.push({start,end,content_end:i,raw:t.slice(start,end),content:t.slice(start,i),eol:e,line});line++;start=end;if(e.length===2)i++}}if(start<t.length||!a.length)a.push({start,end:t.length,content_end:t.length,raw:t.slice(start),content:t.slice(start),eol:'',line});return a};
const lineNo=(lines,pos)=>{let lo=0,hi=lines.length-1;while(lo<=hi){const m=(lo+hi)>>1;if(pos<lines[m].start)hi=m-1;else if(pos>=lines[m].end&&m<lines.length-1)lo=m+1;else return lines[m].line}return lines.length};
const endings=s=>{const crlf=(String(s).match(/\r\n/g)||[]).length,cr=(String(s).replace(/\r\n/g,'').match(/\r/g)||[]).length,lf=(String(s).replace(/\r\n/g,'').match(/\n/g)||[]).length;const kinds=[crlf&&'CRLF',lf&&'LF',cr&&'CR'].filter(Boolean);return kinds.length>1?'MIXED':(kinds[0]||'NONE')};
// Package paths are virtual file_refs, not host filesystem paths. Empty/NUL are
// malformed; absolute/URL/`..` that escape the package root are unsafe.
const pathMalformed=p=>{const v=clean(p);return !v||v.includes('\0')};
const normalizeSeparators=p=>clean(p).replace(/\\/g,'/');
const isAbsOrUrl=p=>/^[A-Za-z][A-Za-z0-9+.-]*:\/\//.test(p)||p.startsWith('/')||/^[A-Za-z]:\//.test(p);
const dirname=p=>{const i=p.lastIndexOf('/');return i<0?'':p.slice(0,i)};
const collapsePath=v=>{const parts=[];for(const bit of String(v).split('/')){if(!bit||bit==='.')continue;if(bit==='..'){if(!parts.length)return null;parts.pop();continue}parts.push(bit)}return parts.join('/')};
const classifyPackagePath=p=>{if(pathMalformed(p))return{error:'invalid'};const n=normalizeSeparators(p);if(isAbsOrUrl(n))return{error:'unsafe'};const collapsed=collapsePath(n);if(collapsed===null||collapsed==='')return{error:'unsafe'};return{path:collapsed}};
const safePath=p=>{const c=classifyPackagePath(p);return c.path||null};
const resolvePath=(base,rel)=>{if(pathMalformed(rel))return{error:'invalid'};const r=normalizeSeparators(rel);if(isAbsOrUrl(r))return{error:'unsafe'};const baseClass=classifyPackagePath(base);const b=baseClass.path||(pathMalformed(base)? '':normalizeSeparators(base));const d=dirname(b);const joined=d?`${d}/${r}`:r;const collapsed=collapsePath(joined);if(collapsed===null||collapsed===''||isAbsOrUrl(collapsed))return{error:'unsafe'};return{path:collapsed}};
const parseHeader=s=>{const m=String(s).replace(/^\ufeff/,'').match(/^\s*([A-Za-z][A-Za-z0-9_]*)[ \t]*(?:--.*)?$/);return m?m[1].toUpperCase():''};
const commentsIn=(raw,base)=>{const out=[];const lines=lineList(raw);for(const l of lines){const m=l.content.match(/^[ \t]*(--.*)$/);if(m){const st=base+l.content.indexOf(m[1]);out.push({start_char:st,end_char:st+m[1].length,raw:m[1]})}}return out};
const defaultsIn=raw=>(String(raw).match(/(?:^|[\s,])(?:\d+\*|\*)(?=[\s,\/]|$)/g)||[]).length;
const makeFile=(path,text,meta,findings)=>{const source=String(text??''),lines=lineList(source),prefix=utf8Prefix(source),headers=[];for(const l of lines){const kw=parseHeader(l.content);if(kw)headers.push({kw,start:l.start,line:l.line})}const nodes=[];const add=(kind,kw,start,end)=>{if(end<=start)return;const raw=source.slice(start,end),first=lineNo(lines,start),last=lineNo(lines,Math.max(start,end-1)),known=Boolean(kw&&allowed.has(kw)),opaque=kind==='keyword'&&!known;const node={node_id:`${path}:${start}:${sha256(raw).slice(0,16)}`,kind:opaque?'opaque_keyword':kind,keyword:kw||null,known,opaque,start_char:start,end_char:end,start_byte:prefix[start]??utf8Length(source.slice(0,start)),end_byte:prefix[end]??utf8Length(source.slice(0,end)),start_line:first,end_line:last,raw_hash:hash(raw),raw,comment_count:commentsIn(raw,start).length,default_marker_count:defaultsIn(raw),include_paths:[]};if(kw==='INCLUDE'){const q=raw.match(/['"]([^'"\r\n]+)['"]/);if(q)node.include_paths=[q[1]]}nodes.push(node)};let cursor=0;for(let i=0;i<headers.length;i++){const h=headers[i],end=i+1<headers.length?headers[i+1].start:source.length;if(h.start>cursor)add('trivia','',cursor,h.start);add('keyword',h.kw,h.start,end);cursor=end}if(cursor<source.length||!headers.length)add('trivia','',cursor,source.length);if(nodes.length>MAX_NODES)findings.push({code:'CST_NODE_LIMIT',severity:'error',file_ref:path});const manifest={file_ref:path,encoding:clean(meta?.encoding)||'utf-8-text',encoding_verified:false,line_endings:endings(source),bom:source.charCodeAt(0)===0xfeff,byte_length:utf8Length(source),char_length:source.length,line_count:lines.length,sha256:hash(source),declared_sha256:clean(meta?.source_hash||meta?.sha256)||null,node_count:nodes.length,source_kind:clean(meta?.source_kind)||'inline_text'};if(manifest.declared_sha256&&manifest.declared_sha256.toLowerCase()!==manifest.sha256.toLowerCase())findings.push({code:'SOURCE_HASH_MISMATCH',severity:'error',file_ref:path,expected:manifest.declared_sha256,actual:manifest.sha256});if(manifest.encoding&&!/^utf-?8(?:-bom)?(?:-text)?$/i.test(manifest.encoding))findings.push({code:'UNSUPPORTED_SOURCE_ENCODING',severity:'error',file_ref:path,encoding:manifest.encoding});return{file_ref:path,text:source,manifest,nodes,include_paths:[...new Set(nodes.flatMap(n=>n.include_paths||[]))]}};
const rawFiles=Array.isArray(x.include_files)?x.include_files:[];const rootClass=classifyPackagePath(x.root_path||'schedule.inc'),root=rootClass.path||null,findings=[];if(rootClass.error==='invalid')findings.push({code:'ROOT_PATH_INVALID',severity:'error'});else if(rootClass.error==='unsafe')findings.push({code:'ROOT_PATH_UNSAFE',severity:'error'});const mainText=typeof x.baseline_schedule_text==='string'?x.baseline_schedule_text:'';if(!mainText)findings.push({code:'BASELINE_TEXT_REQUIRED',severity:'error'});const specs=[{path:root||'schedule.inc',text:mainText,meta:{encoding:x.encoding,source_hash:x.source_hash,source_kind:'root'}}];for(const f of rawFiles){if(!obj(f)||typeof f.text!=='string'){findings.push({code:'INCLUDE_FILE_INVALID',severity:'error'});continue}const classified=classifyPackagePath(f.path);if(classified.error==='invalid'){findings.push({code:'INCLUDE_PATH_INVALID',severity:'error',path:f.path});continue}if(classified.error==='unsafe'||!classified.path){findings.push({code:'INCLUDE_PATH_UNSAFE',severity:'error',path:f.path});continue}specs.push({path:classified.path,text:f.text,meta:{...f,source_kind:'include'}})}const seen=new Set();const files=[];for(const s of specs){if(seen.has(s.path)){findings.push({code:'DUPLICATE_FILE_REF',severity:'error',file_ref:s.path});continue}seen.add(s.path);files.push(makeFile(s.path,s.text,s.meta,findings))}if(files.length>MAX_FILES)findings.push({code:'FILE_LIMIT',severity:'error'});const totalBytes=files.reduce((n,f)=>n+f.manifest.byte_length,0);if(totalBytes>MAX_BYTES)findings.push({code:'PACKAGE_SIZE_LIMIT',severity:'error',byte_length:totalBytes});const byRef=new Map(files.map(f=>[f.file_ref,f])),graph={};for(const f of files){graph[f.file_ref]=[];for(const includeNode of f.nodes.filter(n=>n.keyword==='INCLUDE'))for(const inc of includeNode.include_paths||[]){const resolved=resolvePath(f.file_ref,inc);const target=resolved.path||null;const edge={raw_path:inc,target_file_ref:target,source_node_id:includeNode.node_id||null};graph[f.file_ref].push(edge);if(resolved.error==='invalid'){findings.push({code:'INCLUDE_PATH_INVALID',severity:'error',file_ref:f.file_ref,path:inc});continue}if(resolved.error==='unsafe'||!target){findings.push({code:'INCLUDE_PATH_UNSAFE',severity:'error',file_ref:f.file_ref,path:inc});continue}if(!byRef.has(target))findings.push({code:'INCLUDE_NOT_FOUND',severity:'warning',file_ref:f.file_ref,path:inc,target_file_ref:target,note:'INCLUDE body not attached; keep call-site on the same DATES'})}}
const reachable=new Set(),visit=(p,stack,depth)=>{if(depth>MAX_DEPTH){findings.push({code:'INCLUDE_DEPTH_LIMIT',severity:'error',file_ref:p});return}if(stack.includes(p)){findings.push({code:'INCLUDE_CYCLE',severity:'error',cycle:[...stack,p]});return}if(reachable.has(p))return;reachable.add(p);for(const e of(graph[p]||[]))if(e.target_file_ref&&byRef.has(e.target_file_ref))visit(e.target_file_ref,[...stack,p],depth+1)};if(root)visit(root,[],0);for(const f of files)if(!reachable.has(f.file_ref)&&f.file_ref!==root)findings.push({code:'UNREACHABLE_INCLUDE_FILE',severity:'warning',file_ref:f.file_ref});const allNodes=files.flatMap(f=>f.nodes);const inv={};for(const n of allNodes)if(n.keyword)inv[n.keyword]=(inv[n.keyword]||0)+1;const unknown=[...new Set(allNodes.filter(n=>n.opaque&&n.keyword).map(n=>n.keyword))];const packageHash=hash(files.slice().sort((a,b)=>a.file_ref.localeCompare(b.file_ref)).map(f=>[f.file_ref,f.manifest.sha256]).map(v=>v.join('|')).join('\n'));const compact={root_path:root,package_hash:packageHash,files:files.map(f=>({file_ref:f.file_ref,manifest:f.manifest,nodes:f.nodes.map(n=>({node_id:n.node_id,kind:n.kind,keyword:n.keyword,known:n.known,opaque:n.opaque,start_char:n.start_char,end_char:n.end_char,start_byte:n.start_byte,end_byte:n.end_byte,start_line:n.start_line,end_line:n.end_line,raw_hash:n.raw_hash,comment_count:n.comment_count,default_marker_count:n.default_marker_count,include_paths:n.include_paths}))})),keyword_inventory:inv,opaque_keywords:unknown};const hard=findings.filter(f=>f.severity==='error');return[{json:{contract:'baseline_analysis',contract_version:'1.0',status:hard.length?'needs_input':'analyzed',cst_version:'lossless-lexical-v1',offset_unit:'utf8-byte-and-js-char',package:{contract:'schedule_package',contract_version:'1.0',root_path:root,package_hash:packageHash,files},file_manifest:files.map(f=>f.manifest),compact_inventory:compact,cst:allNodes,keyword_inventory:inv,opaque_keywords:unknown,include_graph:graph,reachable_files:[...reachable].sort(),baseline_hash:files.find(f=>f.file_ref===root)?.manifest.sha256||null,preservation_token:hash(packageHash+'|'+JSON.stringify(graph)),entity_snapshot:{block_count:allNodes.filter(n=>n.kind==='keyword').length,node_count:allNodes.length,files:files.length,unknown_keyword_blocks:allNodes.filter(n=>n.opaque).length},findings,limits:{max_nodes:MAX_NODES,max_bytes:MAX_BYTES,max_files:MAX_FILES,max_include_depth:MAX_DEPTH}}}];
""".replace("__KEYWORDS__", allowed)


def build_merge_js(keywords: list[str]) -> str:
    allowed = json.dumps(keywords, ensure_ascii=False)
    return r"""
const x=$json.merge_request??$json;
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),arr=Array.isArray,clean=v=>typeof v==='string'?v.trim():'';
const allowed=new Set(__KEYWORDS__),findings=[],changes=arr(x.changes)?x.changes:[],mode=clean(x.mode).toUpperCase();
__SHA256_JS__
const hash=contentHash;
const parse=v=>{if(obj(v))return v;if(typeof v==='string'){try{const y=JSON.parse(v);return obj(y)?y:{}}catch{return{}}}return{}};
const analysis=parse(x.baseline_analysis),pkg=obj(analysis.package)?analysis.package:(obj(x.baseline_package)?x.baseline_package:null),mutations=changes.filter(c=>clean(c.operation).toUpperCase()!=='KEEP');
if(!['CREATE','REVISE'].includes(mode))findings.push({code:'MODE_INVALID',severity:'error'});if(mode==='REVISE'&&!pkg)findings.push({code:'BASELINE_ANALYSIS_REQUIRED',severity:'error'});if(mode==='REVISE'&&pkg&&!Array.isArray(pkg.files))findings.push({code:'BASELINE_PACKAGE_INVALID',severity:'error'});
const rootPath=clean(pkg?.root_path||x.root_path||'schedule.inc')||'schedule.inc';const baseFiles=(pkg&&Array.isArray(pkg.files)?pkg.files:mode==='CREATE'?[{file_ref:rootPath,text:'',manifest:{file_ref:rootPath,sha256:hash('')}}]:[]).map(f=>({file_ref:String(f.file_ref),text:String(f.text??''),manifest:obj(f.manifest)?f.manifest:{},nodes:arr(f.nodes)?f.nodes:[]}));const byRef=new Map(baseFiles.map(f=>[f.file_ref,f]));
const nodeMap=new Map();for(const f of baseFiles)for(const n of f.nodes){if(n.node_id)nodeMap.set(String(n.node_id),{file:f,node:n})};const touched=new Map(),edits=new Map(),validated=[];
const targetId=c=>clean(c.target_node_id||c.node_id||c.target?.node_id);const targetFor=c=>{const id=targetId(c);if(!id)return null;return nodeMap.get(id)||null};
const firstKeyword=s=>{for(const line of String(s).split(/\r\n|\n|\r/)){const t=line.trim();if(!t||t.startsWith('--'))continue;const m=t.match(/^([A-Za-z][A-Za-z0-9_]*)\s*(?:--.*)?$/);return m?m[1].toUpperCase():''}return''};
const lineEndings=s=>{const t=String(s),crlf=(t.match(/\r\n/g)||[]).length,without=t.replace(/\r\n/g,''),cr=(without.match(/\r/g)||[]).length,lf=(without.match(/\n/g)||[]).length,k=[crlf&&'CRLF',lf&&'LF',cr&&'CR'].filter(Boolean);return k.length>1?'MIXED':(k[0]||'NONE')};
for(let i=0;i<changes.length;i++){const c=changes[i]||{},op=clean(c.operation).toUpperCase(),kw=clean(c.keyword).toUpperCase();if(!['KEEP','MODIFY','ADD','REMOVE'].includes(op)){findings.push({code:'CHANGE_INVALID',severity:'error',index:i});continue}if(op==='KEEP'){validated.push({...c,operation:'KEEP',disposition:'KEEP'});continue}if(!allowed.has(kw)){findings.push({code:'UNSUPPORTED_KEYWORD',severity:'error',keyword:kw,index:i});continue}
  if(op==='ADD'){const fileRef=clean(c.file_ref||c.target_file_ref||rootPath),file=byRef.get(fileRef);if(!file){findings.push({code:'ADD_FILE_NOT_FOUND',severity:'error',file_ref:fileRef,index:i});continue}const rendered=typeof c.rendered_text==='string'?c.rendered_text:'';if(!rendered){findings.push({code:'ADD_TEXT_REQUIRED',severity:'error',index:i});continue}if(firstKeyword(rendered)!==kw){findings.push({code:'RENDERED_KEYWORD_MISMATCH',severity:'error',keyword:kw,index:i});continue}let at=file.text.length;const before=clean(c.before_node_id),after=clean(c.after_node_id);if(before&&after){findings.push({code:'ADD_ANCHOR_AMBIGUOUS',severity:'error',index:i});continue}if(before||after){const t=nodeMap.get(before||after);if(!t||t.file.file_ref!==fileRef){findings.push({code:'ADD_ANCHOR_NOT_FOUND',severity:'error',index:i});continue}at=before?t.node.start_char:t.node.end_char}const e=edits.get(fileRef)||[];e.push({start:at,end:at,replacement:rendered,change:c,index:i,operation:op});edits.set(fileRef,e);validated.push({...c,operation:'ADD',file_ref:fileRef});continue}
  const hit=targetFor(c);if(!hit){findings.push({code:'CHANGE_TARGET_NODE_REQUIRED',severity:'error',index:i});continue}const n=hit.node;if(String(n.keyword||'').toUpperCase()!==kw){findings.push({code:'TARGET_KEYWORD_MISMATCH',severity:'error',index:i,node_id:n.node_id});continue}if(n.opaque||n.known===false){findings.push({code:'OPAQUE_NODE_MUTATION_FORBIDDEN',severity:'error',index:i,node_id:n.node_id});continue}if(touched.has(n.node_id)){findings.push({code:'TARGET_MUTATED_TWICE',severity:'error',index:i,node_id:n.node_id});continue}if(!clean(c.expected_raw_hash)||clean(c.expected_raw_hash).toLowerCase()!==clean(n.raw_hash).toLowerCase()){findings.push({code:'TARGET_HASH_REQUIRED_OR_STALE',severity:'error',index:i,node_id:n.node_id});continue}touched.set(n.node_id,op);if(op==='MODIFY'){const rendered=typeof c.rendered_text==='string'?c.rendered_text:'';if(!rendered){findings.push({code:'MODIFY_TEXT_REQUIRED',severity:'error',index:i});continue}if(firstKeyword(rendered)!==kw){findings.push({code:'RENDERED_KEYWORD_MISMATCH',severity:'error',keyword:kw,index:i,node_id:n.node_id});continue}edits.set(hit.file.file_ref,[...(edits.get(hit.file.file_ref)||[]),{start:Number(n.start_char),end:Number(n.end_char),replacement:rendered,change:c,index:i,operation:op}]);validated.push({...c,operation:'MODIFY',target_node_id:n.node_id})}else{const approval=obj(x.remove_approval)?x.remove_approval:{};if(x.explicit_remove_approved!==true||!clean(approval.actor)||!clean(approval.reason)||!clean(approval.gate_id)){findings.push({code:'REMOVE_REQUIRES_ACCOUNTABLE_APPROVAL',severity:'error',index:i,node_id:n.node_id});continue}edits.set(hit.file.file_ref,[...(edits.get(hit.file.file_ref)||[]),{start:Number(n.start_char),end:Number(n.end_char),replacement:'',change:c,index:i,operation:op}]);validated.push({...c,operation:'REMOVE',target_node_id:n.node_id,approval:{actor:approval.actor,reason:approval.reason,gate_id:approval.gate_id}})}}
if(!byRef.has(rootPath))findings.push({code:'ROOT_FILE_MISSING',severity:'error'});for(const file of baseFiles){const es=(edits.get(file.file_ref)||[]).slice().sort((a,b)=>b.start-a.start||b.index-a.index);let last=Number.MAX_SAFE_INTEGER;for(const e of es){if(!Number.isInteger(e.start)||!Number.isInteger(e.end)||e.start<0||e.end<e.start||e.end>file.text.length){findings.push({code:'EDIT_OFFSET_INVALID',severity:'error',file_ref:file.file_ref,index:e.index});continue}if(e.end>last)findings.push({code:'OVERLAPPING_EDITS',severity:'error',file_ref:file.file_ref,index:e.index});last=Math.min(last,e.start)}}
const validationHard=findings.filter(f=>f.severity==='error'),candidateFiles=[];if(!validationHard.length){for(const file of baseFiles){const es=(edits.get(file.file_ref)||[]).slice().sort((a,b)=>b.start-a.start||b.index-a.index);let text=file.text;for(const e of es)text=text.slice(0,e.start)+e.replacement+text.slice(e.end);candidateFiles.push({...file,text,manifest:{...file.manifest,file_ref:file.file_ref,sha256:hash(text),byte_length:shaUtf8(text).length,char_length:text.length,line_count:String(text).split(/\r\n|\n|\r/).length,line_endings:lineEndings(text),bom:text.charCodeAt(0)===0xfeff}})}}
const outFiles=validationHard.length?baseFiles:candidateFiles,applied=validationHard.length?[]:validated,root=outFiles.find(f=>f.file_ref===rootPath);if(!mutations.length&&mode==='REVISE'&&pkg&&outFiles.some((f,i)=>f.text!==baseFiles[i]?.text))findings.push({code:'UNEXPECTED_ZERO_CHANGE_MUTATION',severity:'error'});const packageHash=hash(outFiles.slice().sort((a,b)=>a.file_ref.localeCompare(b.file_ref)).map(f=>`${f.file_ref}|${f.manifest.sha256||hash(f.text)}`).join('\n'));const hard=findings.filter(f=>f.severity==='error');const zero=mode==='REVISE'&&mutations.length===0&&pkg&&outFiles.length===baseFiles.length&&outFiles.every((f,i)=>f.file_ref===baseFiles[i].file_ref&&f.text===baseFiles[i].text&&clean(f.manifest?.sha256)===clean(baseFiles[i].manifest?.sha256));const changedKeywords=[...new Set(applied.filter(c=>c.operation!=='KEEP').map(c=>clean(c.keyword).toUpperCase()))];return[{json:{contract:'schedule_merge_result',contract_version:'1.0',status:hard.length?'needs_input':'merged',mode,atomic:true,baseline_package_hash:pkg?.package_hash||null,output_package:{contract:'schedule_package',contract_version:'1.0',root_path:rootPath,package_hash:packageHash,files:outFiles.map(f=>({file_ref:f.file_ref,text:f.text,manifest:f.manifest}))},generated_schedule:root?.text||'',output_hash:root?.manifest?.sha256||hash(root?.text||''),applied_changes:applied,rejected_changes:hard.length?changes:[],preservation_report:mode==='REVISE'?{policy:'preserve_unmentioned',zero_change_byte_identical:Boolean(zero),baseline_node_count:nodeMap.size,explicit_mutation_count:mutations.length,modified_count:applied.filter(c=>c.operation==='MODIFY').length,added_count:applied.filter(c=>c.operation==='ADD').length,removed_count:applied.filter(c=>c.operation==='REMOVE').length,all_baseline_nodes_accounted:hard.length===0,unchanged_file_hashes:baseFiles.filter((f,i)=>outFiles[i]?.text===f.text).map(f=>f.file_ref)}:{policy:'not_applicable'},semantic_diff:{changed_keywords:changedKeywords,include_graph_changed:changedKeywords.includes('INCLUDE')},textual_diff:applied.filter(c=>c.operation!=='KEEP').map(c=>({operation:c.operation,keyword:clean(c.keyword).toUpperCase(),target_node_id:c.target_node_id||c.node_id||null})),findings}}];
""".replace("__KEYWORDS__", allowed).replace("__SHA256_JS__", SHA256_JS)
