"""Catalogue-driven state replay for the portable SCHEDULE validator.

The runtime deliberately contains no tNavigator field positions or keyword
semantics.  Every definition, reference, hierarchy edge, temporal class,
dependency and conflicting state key must be declared in the accountable
22.2 catalogue entry that already owns the record layout and citation.
"""
from __future__ import annotations

import json

from schedule_lossless_runtime import SHA256_JS


def build_schedule_validator_js(keywords: list[str]) -> str:
    allowed = json.dumps(keywords, ensure_ascii=False)
    return r"""
const x=$json.schedule_validation_request??$json;
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),arr=Array.isArray,clean=v=>typeof v==='string'?v.trim():'';
const allowed=new Set(__KEYWORDS__),findings=[];
__SHA256_JS__
const hash=contentHash,shaPattern=/^sha256:[a-f0-9]{64}$/i;
const validationPhase=clean(x.validation_phase||'CANDIDATE').toUpperCase(),baselinePhase=validationPhase==='BASELINE_PREFIX';
const mode=baselinePhase?'CREATE':clean(x.mode||x.build_mode||'CREATE').toUpperCase();
const pkg=obj(x.output_package)?x.output_package:{},files=arr(pkg.files)&&pkg.files.length?pkg.files.filter(obj).map(f=>({file_ref:clean(f.file_ref)||'unknown',text:String(f.text??'')})):[{file_ref:'schedule.inc',text:typeof x.schedule_text==='string'?x.schedule_text:''}];
const catalogue=obj(x.schema_catalogue)?x.schema_catalogue:{schemas:arr(x.approved_keyword_schemas)?x.approved_keyword_schemas:[]};
const schemas=arr(catalogue.schemas)&&catalogue.schemas.length?catalogue.schemas.filter(obj):(arr(x.approved_keyword_schemas)?x.approved_keyword_schemas.filter(obj):[]);
const schemaKeywords=new Set(schemas.map(s=>clean(s.keyword).toUpperCase()).filter(Boolean)),render=obj(x.render_result)?x.render_result:{};
const events=arr(x.ir_events)?x.ir_events.filter(obj):[],temporalPolicy=obj(x.temporal_policy)?x.temporal_policy:{};
const initial=obj(x.semantic_baseline_snapshot)?x.semantic_baseline_snapshot:(obj(x.initial_semantic_snapshot)?x.initial_semantic_snapshot:{});
const catalogueHash=clean(catalogue.catalogue_hash||render.catalogue_hash).toLowerCase(),baselinePackageHash=clean(x.baseline_package_hash||pkg.baseline_package_hash||'');
const decoder=obj(x.baseline_decode_result)?x.baseline_decode_result:{},requestedBoundary=clean(x.change_effective_from||decoder.change_effective_from),modelStart=clean(x.model_start_date||decoder.model_start_date);
const initialBodyForHash={...initial};delete initialBodyForHash.snapshot_hash;const computedInitialHash=hash(JSON.stringify(initialBodyForHash)),declaredInitialHash=clean(initial.snapshot_hash);
const blocks=[],dates=[],includes=[],month={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};
const parseDate=raw=>{const t=clean(raw).toUpperCase();let m=t.match(/^(\d{4})-(\d{2})-(\d{2})$/),y,mo,d;if(m){y=Number(m[1]);mo=Number(m[2])-1;d=Number(m[3])}else{m=t.match(/^(\d{1,2})\s+([A-Z]{3})\s+(\d{4})$/);if(!m||month[m[2]]===undefined)return null;d=Number(m[1]);mo=month[m[2]];y=Number(m[3])}const dt=Date.UTC(y,mo,d),v=new Date(dt);return v.getUTCFullYear()===y&&v.getUTCMonth()===mo&&v.getUTCDate()===d?{raw:t,iso:`${String(y).padStart(4,'0')}-${String(mo+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,epoch:dt}:null};
if(!baselinePhase){for(const file of files){const lines=file.text.replace(/\r\n?/g,'\n').split('\n'),headers=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^\s*([A-Za-z][A-Za-z0-9_]*)\s*(?:--.*)?$/),kw=m?m[1].toUpperCase():'';if(allowed.has(kw))headers.push({keyword:kw,line:i})}for(let h=0;h<headers.length;h++){const start=headers[h].line,end=h+1<headers.length?headers[h+1].line:lines.length,kw=headers[h].keyword,body=lines.slice(start+1,end),nonempty=body.map(v=>v.trim()).filter(v=>v&&!v.startsWith('--'));blocks.push({file_ref:file.file_ref,keyword:kw,start_line:start+1,end_line:end,record_lines:nonempty.length});if(!schemaKeywords.has(kw))findings.push({code:'KEYWORD_SCHEMA_NOT_APPROVED',severity:'error',file_ref:file.file_ref,keyword:kw,line:start+1});if(!nonempty.length)findings.push({code:'KEYWORD_RECORD_MISSING',severity:'error',file_ref:file.file_ref,keyword:kw,line:start+1});if(kw==='INCLUDE'){const q=body.join('\n').match(/['"]([^'"\r\n]+)['"]/);if(q)includes.push({file_ref:file.file_ref,path:q[1]});else findings.push({code:'INCLUDE_TARGET_MISSING',severity:'error',file_ref:file.file_ref,line:start+1})}if(kw==='DATES')for(let j=0;j<body.length;j++){const candidate=body[j].replace(/--.*$/,'').replace(/\/.*$/,'').trim();if(!candidate)continue;const d=parseDate(candidate);if(d)dates.push({...d,file_ref:file.file_ref,line:start+2+j});else findings.push({code:'DATES_VALUE_INVALID',severity:'error',file_ref:file.file_ref,line:start+2+j,value:candidate})}}}if(!files.some(f=>f.text.trim()))findings.push({code:'SCHEDULE_TEXT_REQUIRED',severity:'error'});for(const inc of includes)if(!clean(inc.path)||String(inc.path).includes('\0'))findings.push({code:'INCLUDE_PATH_INVALID',severity:'error',...inc});for(let i=1;i<dates.length;i++)if(dates[i].epoch<=dates[i-1].epoch)findings.push({code:'DATES_NOT_STRICTLY_INCREASING',severity:'error',previous:dates[i-1],current:dates[i]})}
const profile=obj(x.simulator_profile)?x.simulator_profile:{};if(clean(profile.vendor)!=='Rock Flow Dynamics'||clean(profile.simulator).toLowerCase()!=='tnavigator'||clean(profile.version)!=='22.2')findings.push({code:'PROFILE_NOT_APPROVED',severity:'error'});
if(!clean(x.schema_catalogue_ref||catalogue.catalogue_ref)||x.schema_catalogue_approved!==true||(!baselinePhase&&render.status!=='rendered'))findings.push({code:'SCHEMA_CATALOGUE_NOT_APPROVED',severity:'error'});
if(!schemas.length)findings.push({code:'APPROVED_KEYWORD_SCHEMAS_REQUIRED',severity:'error'});
if(!['BASELINE_PREFIX','CANDIDATE'].includes(validationPhase))findings.push({code:'SEMANTIC_VALIDATION_PHASE_INVALID',severity:'error'});
if(!['CREATE','REVISE'].includes(mode))findings.push({code:'SEMANTIC_BUILD_MODE_INVALID',severity:'error'});
if(baselinePhase){const compact=e=>({event_id:e.event_id,keyword:e.keyword,variant:e.variant,effective_at:e.effective_at,source_node_id:e.source_node_id,record_index:e.record_index,record_hash:e.record_hash}),prefixHash=hash(JSON.stringify(events.map(compact))),initialHash=declaredInitialHash||computedInitialHash;if(decoder.contract!=='baseline_decode_result'||decoder.contract_version!=='1.0'||decoder.status!=='decoded')findings.push({code:'BASELINE_DECODER_RESULT_REQUIRED',severity:'error'});if(!shaPattern.test(clean(decoder.prefix_hash))||!shaPattern.test(clean(decoder.decoded_hash)))findings.push({code:'BASELINE_DECODER_HASH_REQUIRED',severity:'error'});if(prefixHash!==clean(decoder.prefix_hash))findings.push({code:'BASELINE_DECODER_PREFIX_MISMATCH',severity:'error'});if(initialHash!==clean(decoder.initial_snapshot_hash))findings.push({code:'BASELINE_DECODER_INITIAL_SNAPSHOT_MISMATCH',severity:'error'});if(clean(decoder.catalogue_hash).toLowerCase()!==catalogueHash)findings.push({code:'BASELINE_DECODER_CATALOGUE_MISMATCH',severity:'error'});if(clean(decoder.baseline_package_hash)!==baselinePackageHash) findings.push({code:'BASELINE_DECODER_PACKAGE_MISMATCH',severity:'error'});if(!parseDate(requestedBoundary)||!parseDate(modelStart))findings.push({code:'BASELINE_REPLAY_BOUNDARY_REQUIRED',severity:'error'})}

// Validate the generic semantic declarations.  There are intentionally no
// built-in mappings such as WELSPECS=>well or GRUPTREE=>group edge here.
const schemaMap=new Map(),semanticRules=[];
const fieldNames=s=>new Set((arr(s.fields)?s.fields:[]).map(f=>clean(f?.name)).filter(Boolean));
const validField=(names,name)=>clean(name)&&names.has(clean(name));
for(let i=0;i<schemas.length;i++){
  const s=schemas[i],kw=clean(s.keyword).toUpperCase(),variant=clean(s.variant)||'default',key=`${kw}::${variant}`,names=fieldNames(s),sem=obj(s.semantics)?s.semantics:null;
  schemaMap.set(key,s);
  if(!sem){findings.push({code:'SCHEMA_SEMANTICS_REQUIRED',severity:'error',keyword:kw,variant});continue}
  let bad=false;const period=clean(sem.period||'ANY').toUpperCase();if(!['ANY','HISTORY','FORECAST'].includes(period)){findings.push({code:'SEMANTIC_PERIOD_INVALID',severity:'error',keyword:kw,variant});bad=true}
  const clock=obj(sem.clock)?sem.clock:{};for(const f of [clock.sets_from_field,clock.effective_date_field].filter(Boolean))if(!validField(names,f)){findings.push({code:'SEMANTIC_FIELD_UNKNOWN',severity:'error',keyword:kw,variant,field:f});bad=true}
  const definitions=arr(sem.definitions)?sem.definitions:[],references=arr(sem.references)?sem.references:[],edges=arr(sem.hierarchy_edges)?sem.hierarchy_edges:[],states=arr(sem.state_assignments)?sem.state_assignments:[],prereqs=arr(sem.prerequisites)?sem.prerequisites:[],lifecycles=arr(sem.lifecycle_effects)?sem.lifecycle_effects:[],intervalRules=arr(sem.interval_rules)?sem.interval_rules:[],numericRules=arr(sem.numeric_constraints)?sem.numeric_constraints:[],wildcardRules=arr(sem.wildcard_rules)?sem.wildcard_rules:[];
  for(const d of definitions){if(!obj(d)||!clean(d.entity_type)||!validField(names,d.id_field)||!['CREATE','UPSERT'].includes(clean(d.action||'UPSERT').toUpperCase())){findings.push({code:'SEMANTIC_DEFINITION_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const r of references){if(!obj(r)||!clean(r.entity_type)||!validField(names,r.id_field)){findings.push({code:'SEMANTIC_REFERENCE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const e of edges){if(!obj(e)||!clean(e.graph)||!clean(e.child_entity_type)||!clean(e.parent_entity_type)||!validField(names,e.child_field)||!validField(names,e.parent_field)){findings.push({code:'SEMANTIC_HIERARCHY_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const a of states){const keys=arr(a?.key_fields)?a.key_fields:[],values=arr(a?.value_fields)?a.value_fields:[];if(!obj(a)||!clean(a.namespace)||!clean(a.entity_type)||!validField(names,a.entity_field)||!keys.every(f=>validField(names,f))||!values.length||!values.every(f=>validField(names,f))){findings.push({code:'SEMANTIC_STATE_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const p of prereqs){const scope=clean(p?.scope||'GLOBAL').toUpperCase();if(!obj(p)||!allowed.has(clean(p.keyword).toUpperCase())||!['GLOBAL','ENTITY'].includes(scope)||(scope==='ENTITY'&&(!validField(names,p.entity_field)||!clean(p.prerequisite_entity_field||p.entity_field)))){findings.push({code:'SEMANTIC_PREREQUISITE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const l of lifecycles){const action=clean(l?.action).toUpperCase();if(!obj(l)||!clean(l.entity_type)||!validField(names,l.id_field)||!['RETIRE','DELETE','REACTIVATE'].includes(action)){findings.push({code:'SEMANTIC_LIFECYCLE_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const q of intervalRules){const scope=clean(q?.scope||'EFFECTIVE_DATE').toUpperCase();if(!obj(q)||!clean(q.namespace)||!clean(q.entity_type)||!validField(names,q.entity_field)||!validField(names,q.start_field)||!validField(names,q.end_field)||clean(q.start_field)===clean(q.end_field)||!['EFFECTIVE_DATE','GLOBAL'].includes(scope)){findings.push({code:'SEMANTIC_INTERVAL_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const n of numericRules){const min=n?.min,max=n?.max;if(!obj(n)||!validField(names,n.field)||(min!==undefined&&!Number.isFinite(Number(min)))||(max!==undefined&&!Number.isFinite(Number(max)))||(min!==undefined&&max!==undefined&&Number(min)>Number(max))){findings.push({code:'SEMANTIC_NUMERIC_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  for(const w of wildcardRules){if(!obj(w)||!validField(names,w.field)||!clean(w.entity_type)){findings.push({code:'SEMANTIC_WILDCARD_RULE_INVALID',severity:'error',keyword:kw,variant});bad=true}}
  if(!bad)semanticRules.push({key,keyword:kw,variant,period,clock,definitions,references,edges,states,prereqs,lifecycles,intervalRules,numericRules,wildcardRules});
}
const ruleMap=new Map(semanticRules.map(r=>[r.key,r]));
if(events.length===0&&!baselinePhase)findings.push({code:'SEMANTIC_IR_REQUIRED',severity:'error'});
const eventIds=new Set(),renderedIds=new Set((arr(render.rendered_records)?render.rendered_records:[]).map(r=>clean(r.event_id)).filter(Boolean));
for(const e of events){const id=clean(e.event_id);if(!id||eventIds.has(id))findings.push({code:'SEMANTIC_EVENT_ID_INVALID',severity:'error',event_id:id});eventIds.add(id);const op=clean(e.operation).toUpperCase();if(baselinePhase){if(op!=='ADD'||!id.startsWith('baseline:')||!clean(e.source_node_id)||!shaPattern.test(clean(e.expected_raw_hash))||!shaPattern.test(clean(e.record_hash))||!arr(e.provenance)||!e.provenance.length)findings.push({code:'BASELINE_EVENT_PROVENANCE_INVALID',severity:'error',event_id:id})}else if(['ADD','MODIFY'].includes(op)&&!renderedIds.has(id))findings.push({code:'SEMANTIC_EVENT_NOT_RENDERED',severity:'error',event_id:id})}
if(!baselinePhase)for(const id of renderedIds)if(!eventIds.has(id))findings.push({code:'RENDERED_EVENT_NOT_IN_IR',severity:'error',event_id:id});

const snapshotContract=initial.contract==='schedule_semantic_snapshot'&&initial.contract_version==='1.0';
if(declaredInitialHash&&declaredInitialHash!==computedInitialHash)findings.push({code:'SEMANTIC_SNAPSHOT_HASH_MISMATCH',severity:'error',expected:declaredInitialHash,actual:computedInitialHash});
if(!baselinePhase&&mode==='REVISE'&&!snapshotContract)findings.push({code:'SEMANTIC_BASELINE_SNAPSHOT_REQUIRED',severity:'error'});
if(snapshotContract&&clean(initial.catalogue_hash).toLowerCase()!==catalogueHash)findings.push({code:'SEMANTIC_SNAPSHOT_CATALOGUE_MISMATCH',severity:'error'});
if(!baselinePhase&&mode==='REVISE'&&!baselinePackageHash)findings.push({code:'SEMANTIC_BASELINE_PACKAGE_HASH_REQUIRED',severity:'error'});
if(!baselinePhase&&mode==='REVISE'&&snapshotContract&&clean(initial.package_hash)!==baselinePackageHash)findings.push({code:'SEMANTIC_SNAPSHOT_PACKAGE_MISMATCH',severity:'error'});
if(!baselinePhase&&mode==='REVISE'&&snapshotContract&&(clean(initial.snapshot_kind).toUpperCase()!=='PRE_CHANGE_BOUNDARY'||!parseDate(initial.replay_through)||!parseDate(initial.change_effective_from)||!shaPattern.test(clean(initial.boundary_hash))))findings.push({code:'SEMANTIC_PRE_CHANGE_BOUNDARY_REQUIRED',severity:'error'});
const entities=new Map(),hierarchies=new Map(),assignments=new Map(),intervals=new Map(),seen=[];
const entityKey=(type,id)=>`${clean(type).toLowerCase()}::${clean(String(id??''))}`;
const addEntity=(type,id,createdAt,retiredAt,source,action='UPSERT')=>{const key=entityKey(type,id);if(!clean(type)||!clean(String(id??'')))return false;const old=entities.get(key);if(action==='CREATE'&&old&&old.retired_epoch===null){findings.push({code:'ENTITY_ALREADY_EXISTS',severity:'error',entity_type:type,entity_id:String(id),source});return false}const created=parseDate(createdAt),retired=parseDate(retiredAt);entities.set(key,{entity_type:clean(type).toLowerCase(),entity_id:clean(String(id)),created_at:created?.iso||null,created_epoch:created?.epoch??Number.NEGATIVE_INFINITY,retired_at:retired?.iso||null,retired_epoch:retired?.epoch??null,source});return true};
const applyLifecycle=(rule,id,effective,eventId)=>{const key=entityKey(rule.entity_type,id),action=clean(rule.action).toUpperCase(),old=entities.get(key);if(!old){findings.push({code:'LIFECYCLE_ENTITY_MISSING',severity:'error',event_id:eventId,entity_type:rule.entity_type,entity_id:String(id??''),action});return}if(action==='REACTIVATE'){if(old.retired_epoch===null||old.retired_epoch>effective.epoch)findings.push({code:'ENTITY_REACTIVATION_INVALID',severity:'error',event_id:eventId,entity_type:rule.entity_type,entity_id:String(id??'')});else addEntity(rule.entity_type,id,effective.iso,null,eventId,'UPSERT');return}if(old.created_epoch>effective.epoch||old.retired_epoch!==null){findings.push({code:'ENTITY_RETIREMENT_INVALID',severity:'error',event_id:eventId,entity_type:rule.entity_type,entity_id:String(id??''),action});return}old.retired_at=effective.iso;old.retired_epoch=effective.epoch;old.source=eventId};
if(snapshotContract){for(const e of(arr(initial.entities)?initial.entities:[]))if(obj(e))addEntity(e.entity_type,e.entity_id,e.created_at,e.retired_at,'snapshot','UPSERT');for(const h of(arr(initial.hierarchy_edges)?initial.hierarchy_edges:[])){if(!obj(h))continue;const graph=clean(h.graph),child=clean(h.child_key)||entityKey(h.child_entity_type,h.child_id),parent=clean(h.parent_key)||entityKey(h.parent_entity_type,h.parent_id);if(graph&&child&&parent){if(!hierarchies.has(graph))hierarchies.set(graph,new Map());hierarchies.get(graph).set(child,parent)}}for(const a of(arr(initial.state_assignments)?initial.state_assignments:[])){if(!obj(a)||!clean(a.assignment_key))continue;assignments.set(clean(a.assignment_key),{signature:clean(a.value_signature||a.signature),source:'snapshot'})}for(const q of(arr(initial.interval_assignments)?initial.interval_assignments:[])){if(!obj(q)||!clean(q.interval_key)||!Number.isFinite(Number(q.start))||!Number.isFinite(Number(q.end)))continue;intervals.set(clean(q.interval_key),[...(intervals.get(clean(q.interval_key))||[]),{start:Number(q.start),end:Number(q.end),source:'snapshot'}])}for(const s of(arr(initial.keyword_occurrences)?initial.keyword_occurrences:[])){if(!obj(s)||!allowed.has(clean(s.keyword).toUpperCase()))continue;seen.push({index:-1,event_id:clean(s.event_id)||'snapshot',keyword:clean(s.keyword).toUpperCase(),fields:obj(s.fields)?s.fields:{},effective_at:clean(s.effective_at)||null})}}
const existsAt=(type,id,epoch)=>{const e=entities.get(entityKey(type,id));return Boolean(e&&e.created_epoch<=epoch&&(e.retired_epoch===null||epoch<e.retired_epoch))};
const historyEnd=parseDate(temporalPolicy.history_end),forecastStart=parseDate(temporalPolicy.forecast_start);
if(historyEnd&&forecastStart&&historyEnd.epoch>=forecastStart.epoch)findings.push({code:'TEMPORAL_CUTOVER_INVALID',severity:'error',history_end:historyEnd.iso,forecast_start:forecastStart.iso});
const activeRuleKeys=new Set(events.filter(e=>!['KEEP','REMOVE'].includes(clean(e.operation).toUpperCase())).map(e=>`${clean(e.keyword).toUpperCase()}::${clean(e.variant)||'default'}`));
const activeRules=semanticRules.filter(r=>activeRuleKeys.has(r.key)),needsHistory=activeRules.some(r=>r.period==='HISTORY'),needsForecast=activeRules.some(r=>r.period==='FORECAST');
if(needsHistory&&!historyEnd)findings.push({code:'HISTORY_END_REQUIRED',severity:'error'});if(needsForecast&&!forecastStart)findings.push({code:'FORECAST_START_REQUIRED',severity:'error'});
const replayBoundary=!baselinePhase&&mode==='REVISE'&&snapshotContract?parseDate(initial.replay_through):null;
const changeBoundary=!baselinePhase&&mode==='REVISE'&&snapshotContract?parseDate(initial.change_effective_from):baselinePhase?parseDate(requestedBoundary):null;
let current=snapshotContract?parseDate(initial.replay_through):(baselinePhase?parseDate(modelStart):null),referenceChecks=0,dependencyChecks=0,hierarchyChecks=0,stateChecks=0,lifecycleChecks=0,intervalChecks=0,numericChecks=0,wildcardChecks=0;
const scalar=(fields,name)=>Object.prototype.hasOwnProperty.call(fields,name)?fields[name]:undefined;
const canonical=v=>{if(obj(v)&&clean(v.state).toLowerCase()==='default')return`default:${Number(v.count||1)}`;if(v===null)return'null';if(typeof v==='object')return JSON.stringify(v);return String(v??'')};
for(let index=0;index<events.length;index++){
  const event=events[index],eventId=clean(event.event_id),op=clean(event.operation).toUpperCase(),kw=clean(event.keyword).toUpperCase(),variant=clean(event.variant)||'default',fields=obj(event.fields)?event.fields:{};
  if(['KEEP','REMOVE'].includes(op))continue;
  const rule=ruleMap.get(`${kw}::${variant}`);if(!rule){findings.push({code:'SEMANTIC_RULE_NOT_FOUND',severity:'error',event_id:eventId,keyword:kw,variant});continue}
  let effective=null;
  if(clean(rule.clock.sets_from_field)){effective=parseDate(scalar(fields,clean(rule.clock.sets_from_field)));if(!effective)findings.push({code:'SEMANTIC_CLOCK_VALUE_INVALID',severity:'error',event_id:eventId,field:clean(rule.clock.sets_from_field)});else{if(current&&effective.epoch<=current.epoch)findings.push({code:'SEMANTIC_CLOCK_NOT_STRICTLY_INCREASING',severity:'error',event_id:eventId,previous:current.iso,current:effective.iso});current=effective}}
  else if(clean(rule.clock.effective_date_field)){effective=parseDate(scalar(fields,clean(rule.clock.effective_date_field)));if(!effective)findings.push({code:'SEMANTIC_EFFECTIVE_DATE_INVALID',severity:'error',event_id:eventId,field:clean(rule.clock.effective_date_field)})}
  else if(rule.clock.uses_current===true)effective=current;
  else if(rule.clock.uses_event_effective_at===true)effective=parseDate(event.effective_at);
  if(!baselinePhase&&mode==='REVISE'&&replayBoundary&&effective&&effective.epoch<=replayBoundary.epoch)findings.push({code:'SEMANTIC_EVENT_NOT_AFTER_BOUNDARY',severity:'error',event_id:eventId,effective_at:effective.iso,replay_through:replayBoundary.iso});
  if(!baselinePhase&&mode==='REVISE'&&changeBoundary&&effective&&effective.epoch<changeBoundary.epoch)findings.push({code:'SEMANTIC_EVENT_BEFORE_CHANGE_BOUNDARY',severity:'error',event_id:eventId,effective_at:effective.iso,change_effective_from:changeBoundary.iso});
  if(baselinePhase&&changeBoundary&&effective&&effective.epoch>=changeBoundary.epoch)findings.push({code:'BASELINE_PREFIX_EVENT_AT_OR_AFTER_BOUNDARY',severity:'error',event_id:eventId,effective_at:effective.iso,change_effective_from:changeBoundary.iso});
  const hasEffects=rule.period!=='ANY'||rule.definitions.length||rule.references.length||rule.edges.length||rule.states.length||rule.prereqs.length||rule.lifecycles.length||rule.intervalRules.length||rule.numericRules.length||rule.wildcardRules.length;
  if(hasEffects&&!effective){findings.push({code:'SEMANTIC_EFFECTIVE_DATE_REQUIRED',severity:'error',event_id:eventId,keyword:kw});continue}
  if(rule.period==='HISTORY'&&historyEnd&&effective.epoch>historyEnd.epoch)findings.push({code:'HISTORY_EVENT_AFTER_CUTOVER',severity:'error',event_id:eventId,effective_at:effective.iso,history_end:historyEnd.iso});
  if(rule.period==='FORECAST'&&forecastStart&&effective.epoch<forecastStart.epoch)findings.push({code:'FORECAST_EVENT_BEFORE_START',severity:'error',event_id:eventId,effective_at:effective.iso,forecast_start:forecastStart.iso});
  for(const w of rule.wildcardRules){wildcardChecks++;const value=scalar(fields,clean(w.field));if(typeof value==='string'&&/[?*]/.test(value))findings.push({code:'WILDCARD_EXPANSION_REQUIRED',severity:'error',event_id:eventId,field:clean(w.field),entity_type:clean(w.entity_type).toLowerCase(),pattern:value})}
  for(const n of rule.numericRules){numericChecks++;const value=scalar(fields,clean(n.field));if(obj(value)&&clean(value.state).toLowerCase()==='default'){if(n.allow_default!==true)findings.push({code:'NUMERIC_DEFAULT_NOT_ALLOWED',severity:'error',event_id:eventId,field:clean(n.field)});continue}const number=Number(value);if(value===undefined||value===null||!Number.isFinite(number)){findings.push({code:'NUMERIC_VALUE_INVALID',severity:'error',event_id:eventId,field:clean(n.field),value});continue}if(n.min!==undefined&&(n.min_exclusive===true?number<=Number(n.min):number<Number(n.min)))findings.push({code:'NUMERIC_VALUE_BELOW_MIN',severity:'error',event_id:eventId,field:clean(n.field),value:number,min:Number(n.min),exclusive:n.min_exclusive===true});if(n.max!==undefined&&(n.max_exclusive===true?number>=Number(n.max):number>Number(n.max)))findings.push({code:'NUMERIC_VALUE_ABOVE_MAX',severity:'error',event_id:eventId,field:clean(n.field),value:number,max:Number(n.max),exclusive:n.max_exclusive===true})}
  for(const p of rule.prereqs){dependencyChecks++;const pkw=clean(p.keyword).toUpperCase(),scope=clean(p.scope||'GLOBAL').toUpperCase();let ok=false;if(scope==='GLOBAL')ok=seen.some(s=>s.keyword===pkw&&s.index<index);else{const value=canonical(scalar(fields,clean(p.entity_field))),other=clean(p.prerequisite_entity_field||p.entity_field);ok=seen.some(s=>s.keyword===pkw&&s.index<index&&canonical(scalar(s.fields,other))===value)}if(!ok)findings.push({code:'KEYWORD_PREREQUISITE_MISSING',severity:'error',event_id:eventId,keyword:kw,required_keyword:pkw,scope})}
  for(const r of rule.references){referenceChecks++;const id=scalar(fields,clean(r.id_field));if((id===undefined||id===null||clean(String(id))==='')&&r.required!==false){findings.push({code:'ENTITY_REFERENCE_VALUE_REQUIRED',severity:'error',event_id:eventId,entity_type:r.entity_type,field:r.id_field});continue}if(id!==undefined&&id!==null&&!existsAt(r.entity_type,id,effective.epoch))findings.push({code:'ENTITY_REFERENCE_MISSING',severity:'error',event_id:eventId,entity_type:clean(r.entity_type).toLowerCase(),entity_id:String(id),effective_at:effective.iso})}
  for(const d of rule.definitions){const id=scalar(fields,clean(d.id_field));if(id===undefined||id===null||clean(String(id))==='')findings.push({code:'ENTITY_DEFINITION_VALUE_REQUIRED',severity:'error',event_id:eventId,entity_type:d.entity_type,field:d.id_field});else addEntity(d.entity_type,id,effective.iso,null,eventId,clean(d.action||'UPSERT').toUpperCase())}
  for(const e of rule.edges){hierarchyChecks++;const graph=clean(e.graph),childId=scalar(fields,clean(e.child_field)),parentId=scalar(fields,clean(e.parent_field)),child=entityKey(e.child_entity_type,childId),parent=entityKey(e.parent_entity_type,parentId);if(!existsAt(e.child_entity_type,childId,effective.epoch)||!existsAt(e.parent_entity_type,parentId,effective.epoch)){findings.push({code:'HIERARCHY_ENTITY_MISSING',severity:'error',event_id:eventId,graph,child_id:String(childId??''),parent_id:String(parentId??'')});continue}if(!hierarchies.has(graph))hierarchies.set(graph,new Map());const edges=hierarchies.get(graph),old=edges.get(child);if(old&&old!==parent)findings.push({code:'HIERARCHY_PARENT_CONFLICT',severity:'error',event_id:eventId,graph,child_id:String(childId),existing_parent:old,new_parent:parent});let cursor=parent,cycle=child===parent;const visited=new Set();while(!cycle&&edges.has(cursor)&&!visited.has(cursor)){visited.add(cursor);cursor=edges.get(cursor);if(cursor===child)cycle=true}if(cycle)findings.push({code:'HIERARCHY_CYCLE',severity:'error',event_id:eventId,graph,child_id:String(childId),parent_id:String(parentId)});else if(!old)edges.set(child,parent)}
  for(const a of rule.states){stateChecks++;const entityId=scalar(fields,clean(a.entity_field));if(!existsAt(a.entity_type,entityId,effective.epoch)){findings.push({code:'STATE_ENTITY_MISSING',severity:'error',event_id:eventId,entity_type:a.entity_type,entity_id:String(entityId??'')});continue}const keyParts=[clean(a.namespace),entityKey(a.entity_type,entityId),effective.iso,...a.key_fields.map(f=>canonical(scalar(fields,clean(f))))],assignmentKey=keyParts.join('|'),signature=a.value_fields.map(f=>`${clean(f)}=${canonical(scalar(fields,clean(f)))}`).join('|'),old=assignments.get(assignmentKey);if(old){if(old.signature===signature&&a.allow_identical_duplicate!==true)findings.push({code:'DUPLICATE_STATE_ASSIGNMENT',severity:'error',event_id:eventId,assignment_key:assignmentKey,previous_source:old.source});else if(old.signature!==signature)findings.push({code:'CONFLICTING_STATE_ASSIGNMENT',severity:'error',event_id:eventId,assignment_key:assignmentKey,previous_source:old.source,previous_value:old.signature,new_value:signature})}else assignments.set(assignmentKey,{signature,source:eventId,namespace:clean(a.namespace),entity_type:clean(a.entity_type).toLowerCase(),entity_id:clean(String(entityId)),effective_at:effective.iso})}
  for(const q of rule.intervalRules){intervalChecks++;const entityId=scalar(fields,clean(q.entity_field)),start=Number(scalar(fields,clean(q.start_field))),end=Number(scalar(fields,clean(q.end_field)));if(!existsAt(q.entity_type,entityId,effective.epoch)){findings.push({code:'INTERVAL_ENTITY_MISSING',severity:'error',event_id:eventId,entity_type:q.entity_type,entity_id:String(entityId??'')});continue}if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end){findings.push({code:'INTERVAL_BOUNDS_INVALID',severity:'error',event_id:eventId,start_field:q.start_field,end_field:q.end_field,start,end});continue}const key=[clean(q.namespace),entityKey(q.entity_type,entityId),clean(q.scope||'EFFECTIVE_DATE').toUpperCase()==='GLOBAL'?'global':effective.iso].join('|'),old=intervals.get(key)||[],conflict=old.find(v=>q.allow_touching===true?start<v.end&&end>v.start:start<=v.end&&end>=v.start);if(conflict)findings.push({code:'INTERVAL_OVERLAP',severity:'error',event_id:eventId,interval_key:key,start,end,previous_start:conflict.start,previous_end:conflict.end,previous_source:conflict.source});else intervals.set(key,[...old,{start,end,source:eventId,namespace:clean(q.namespace),entity_type:clean(q.entity_type).toLowerCase(),entity_id:clean(String(entityId)),effective_at:effective.iso}])}
  for(const l of rule.lifecycles){lifecycleChecks++;const id=scalar(fields,clean(l.id_field));if(id===undefined||id===null||clean(String(id))==='')findings.push({code:'LIFECYCLE_ENTITY_VALUE_REQUIRED',severity:'error',event_id:eventId,entity_type:l.entity_type,field:l.id_field});else applyLifecycle(l,id,effective,eventId)}
  seen.push({index,event_id:eventId,keyword:kw,fields,effective_at:effective?.iso||null});
}
const entityList=[...entities.values()].map(({created_epoch,retired_epoch,...e})=>e).sort((a,b)=>`${a.entity_type}:${a.entity_id}`.localeCompare(`${b.entity_type}:${b.entity_id}`));
const hierarchyList=[];for(const [graph,edges] of [...hierarchies.entries()].sort(([a],[b])=>a.localeCompare(b)))for(const [child,parent] of [...edges.entries()].sort(([a],[b])=>a.localeCompare(b)))hierarchyList.push({graph,child_key:child,parent_key:parent});
const assignmentList=[...assignments.entries()].map(([assignment_key,a])=>({assignment_key,value_signature:a.signature,source:a.source,namespace:a.namespace||null,entity_type:a.entity_type||null,entity_id:a.entity_id||null,effective_at:a.effective_at||null})).sort((a,b)=>a.assignment_key.localeCompare(b.assignment_key));
const intervalList=[];for(const [interval_key,values] of [...intervals.entries()].sort(([a],[b])=>a.localeCompare(b)))for(const q of values.slice().sort((a,b)=>a.start-b.start||a.end-b.end))intervalList.push({interval_key,start:q.start,end:q.end,source:q.source,namespace:q.namespace||null,entity_type:q.entity_type||null,entity_id:q.entity_id||null,effective_at:q.effective_at||null});
const occurrenceList=seen.slice(-10000).map(s=>({event_id:s.event_id,keyword:s.keyword,fields:s.fields,effective_at:s.effective_at}));
const boundaryBody=baselinePhase?{prefix_hash:clean(decoder.prefix_hash),initial_snapshot_hash:clean(decoder.initial_snapshot_hash),catalogue_hash:catalogueHash,package_hash:baselinePackageHash,change_effective_from:changeBoundary?.iso||null,model_start_date:parseDate(modelStart)?.iso||null}:null;
const snapshotBody={contract:'schedule_semantic_snapshot',contract_version:'1.0',snapshot_kind:baselinePhase?'PRE_CHANGE_BOUNDARY':'REPLAY_RESULT',catalogue_hash:catalogueHash||null,package_hash:baselinePackageHash||pkg.package_hash||null,replay_through:current?.iso||initial.replay_through||null,change_effective_from:baselinePhase?changeBoundary?.iso||null:initial.change_effective_from||null,boundary_hash:baselinePhase?hash(JSON.stringify(boundaryBody)):initial.boundary_hash||null,entities:entityList,hierarchy_edges:hierarchyList,state_assignments:assignmentList,interval_assignments:intervalList,keyword_occurrences:occurrenceList};
const semanticCodes=new Set(['SCHEMA_SEMANTICS_REQUIRED','SEMANTIC_PERIOD_INVALID','SEMANTIC_FIELD_UNKNOWN','SEMANTIC_DEFINITION_INVALID','SEMANTIC_REFERENCE_INVALID','SEMANTIC_HIERARCHY_RULE_INVALID','SEMANTIC_STATE_RULE_INVALID','SEMANTIC_PREREQUISITE_INVALID','SEMANTIC_IR_REQUIRED','SEMANTIC_EVENT_ID_INVALID','SEMANTIC_EVENT_NOT_RENDERED','RENDERED_EVENT_NOT_IN_IR','SEMANTIC_BASELINE_SNAPSHOT_REQUIRED','SEMANTIC_BASELINE_PACKAGE_HASH_REQUIRED','SEMANTIC_PRE_CHANGE_BOUNDARY_REQUIRED','SEMANTIC_EVENT_NOT_AFTER_BOUNDARY','SEMANTIC_EVENT_BEFORE_CHANGE_BOUNDARY','SEMANTIC_SNAPSHOT_HASH_MISMATCH','SEMANTIC_SNAPSHOT_CATALOGUE_MISMATCH','SEMANTIC_SNAPSHOT_PACKAGE_MISMATCH','BASELINE_DECODER_RESULT_REQUIRED','BASELINE_DECODER_HASH_REQUIRED','BASELINE_DECODER_PREFIX_MISMATCH','BASELINE_DECODER_INITIAL_SNAPSHOT_MISMATCH','BASELINE_DECODER_CATALOGUE_MISMATCH','BASELINE_DECODER_PACKAGE_MISMATCH','BASELINE_REPLAY_BOUNDARY_REQUIRED','BASELINE_EVENT_PROVENANCE_INVALID','BASELINE_PREFIX_EVENT_AT_OR_AFTER_BOUNDARY','ENTITY_ALREADY_EXISTS','SEMANTIC_CLOCK_VALUE_INVALID','SEMANTIC_CLOCK_NOT_STRICTLY_INCREASING','SEMANTIC_EFFECTIVE_DATE_INVALID','SEMANTIC_EFFECTIVE_DATE_REQUIRED','HISTORY_EVENT_AFTER_CUTOVER','FORECAST_EVENT_BEFORE_START','KEYWORD_PREREQUISITE_MISSING','ENTITY_REFERENCE_VALUE_REQUIRED','ENTITY_REFERENCE_MISSING','ENTITY_DEFINITION_VALUE_REQUIRED','HIERARCHY_ENTITY_MISSING','HIERARCHY_PARENT_CONFLICT','HIERARCHY_CYCLE','STATE_ENTITY_MISSING','DUPLICATE_STATE_ASSIGNMENT','CONFLICTING_STATE_ASSIGNMENT','HISTORY_END_REQUIRED','FORECAST_START_REQUIRED','TEMPORAL_CUTOVER_INVALID','SEMANTIC_RULE_NOT_FOUND']);
const extendedSemanticCodes=new Set(['SEMANTIC_LIFECYCLE_RULE_INVALID','SEMANTIC_INTERVAL_RULE_INVALID','SEMANTIC_NUMERIC_RULE_INVALID','SEMANTIC_WILDCARD_RULE_INVALID','LIFECYCLE_ENTITY_MISSING','LIFECYCLE_ENTITY_VALUE_REQUIRED','ENTITY_RETIREMENT_INVALID','ENTITY_REACTIVATION_INVALID','INTERVAL_ENTITY_MISSING','INTERVAL_BOUNDS_INVALID','INTERVAL_OVERLAP','NUMERIC_DEFAULT_NOT_ALLOWED','NUMERIC_VALUE_INVALID','NUMERIC_VALUE_BELOW_MIN','NUMERIC_VALUE_ABOVE_MAX','WILDCARD_EXPANSION_REQUIRED']);
const hard=findings.filter(f=>f.severity==='error'),syntax=hard.some(f=>['SCHEDULE_TEXT_REQUIRED','KEYWORD_RECORD_MISSING','DATES_VALUE_INVALID'].includes(f.code))?0:100,temporal=hard.some(f=>['DATES_NOT_STRICTLY_INCREASING','SEMANTIC_CLOCK_VALUE_INVALID','SEMANTIC_CLOCK_NOT_STRICTLY_INCREASING','SEMANTIC_EFFECTIVE_DATE_INVALID','SEMANTIC_EFFECTIVE_DATE_REQUIRED','SEMANTIC_EVENT_NOT_AFTER_BOUNDARY','HISTORY_EVENT_AFTER_CUTOVER','FORECAST_EVENT_BEFORE_START','HISTORY_END_REQUIRED','FORECAST_START_REQUIRED','TEMPORAL_CUTOVER_INVALID'].includes(f.code))?0:100,profileScore=hard.some(f=>['PROFILE_NOT_APPROVED','SCHEMA_CATALOGUE_NOT_APPROVED','APPROVED_KEYWORD_SCHEMAS_REQUIRED','KEYWORD_SCHEMA_NOT_APPROVED'].includes(f.code))?0:100,semantics=hard.some(f=>semanticCodes.has(f.code)||extendedSemanticCodes.has(f.code))?0:100,score=Math.round(.25*syntax+.25*temporal+.25*profileScore+.25*semantics);
const stateSnapshot={...snapshotBody,snapshot_hash:hash(JSON.stringify(snapshotBody))};
return[{json:{contract:'schedule_validation_result',contract_version:'1.0',validation_phase:validationPhase,status:hard.length?'invalid':'valid',findings,file_count:baselinePhase?Number(decoder.metrics?.files||0):files.length,block_count:baselinePhase?events.length:blocks.length,keyword_counts:baselinePhase?(obj(decoder.keyword_counts)?decoder.keyword_counts:{}):blocks.reduce((a,b)=>(a[b.keyword]=(a[b.keyword]||0)+1,a),{}),dates:dates.map(d=>d.raw),include_paths:includes.map(i=>i.path),render_catalogue_hash:render.catalogue_hash||null,semantic_state_snapshot:hard.length?null:stateSnapshot,semantic_replay:{events:events.length,entities:entityList.length,hierarchy_edges:hierarchyList.length,state_assignments:assignmentList.length,interval_assignments:intervalList.length,reference_checks:referenceChecks,dependency_checks:dependencyChecks,hierarchy_checks:hierarchyChecks,state_checks:stateChecks,lifecycle_checks:lifecycleChecks,interval_checks:intervalChecks,numeric_checks:numericChecks,wildcard_checks:wildcardChecks},score:{stage_score:score,syntax,temporal,profile:profileScore,semantics,thresholds:{attention:85,hitl:70},gate:hard.length||score<70?'hitl':score<85?'attention':'continue'},hard_blockers:[...new Set(hard.map(f=>f.code))]}}];
""".replace("__KEYWORDS__", allowed).replace("__SHA256_JS__", SHA256_JS)
