-- Additive MAS control plane. Safe on a live n8n database: CREATE IF NOT EXISTS only.
-- Never DROP n8n tables. postgres-init runs only on a fresh volume. Lab also applies this via psql.
-- Generated by n8n/templates/generate_mas_control_plane_proxy.py (agent_registry from mas_agent_registry.py) — do not edit by hand.

CREATE TABLE IF NOT EXISTS cases (
    case_id TEXT PRIMARY KEY,
    state JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT cases_status_check CHECK (
        status IN ('new', 'running', 'waiting_user', 'waiting_agent', 'done', 'failed')
    )
);

-- Existing databases: re-create the CHECK so new statuses (waiting_agent) are accepted.
ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_status_check;
ALTER TABLE cases ADD CONSTRAINT cases_status_check CHECK (
    status IN ('new', 'running', 'waiting_user', 'waiting_agent', 'done', 'failed')
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGSERIAL PRIMARY KEY,
    case_id TEXT NOT NULL REFERENCES cases (case_id) ON DELETE CASCADE,
    task_id TEXT,
    kind TEXT NOT NULL,
    actor TEXT NOT NULL,
    agent_id TEXT,
    status TEXT,
    status_message TEXT,
    handoff_message TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS events_case_id_event_id_idx ON events (case_id, event_id);

CREATE TABLE IF NOT EXISTS error_traces (
    error_id BIGSERIAL PRIMARY KEY,
    case_id TEXT,
    execution_id TEXT,
    workflow_name TEXT,
    node_name TEXT,
    error_message TEXT,
    error_type TEXT,
    stack TEXT,
    input_snapshot JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS error_traces_case_id_idx ON error_traces (case_id);
CREATE INDEX IF NOT EXISTS error_traces_execution_id_idx ON error_traces (execution_id);

CREATE TABLE IF NOT EXISTS executions (
    execution_id TEXT PRIMARY KEY,
    case_id TEXT,
    workflow_name TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS executions_case_id_idx ON executions (case_id);

CREATE TABLE IF NOT EXISTS agent_registry (
    agent_id TEXT PRIMARY KEY,
    title TEXT,
    when_to_use TEXT,
    input_required JSONB NOT NULL DEFAULT '[]'::jsonb,
    output_provides JSONB NOT NULL DEFAULT '[]'::jsonb
);
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS invoke JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS input_schema JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS output_schema JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS hitl_policy TEXT NOT NULL DEFAULT 'agent_asks';
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE agent_registry ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '1';

INSERT INTO agent_registry (agent_id, title, when_to_use, input_required, output_provides, invoke, input_schema, output_schema, hitl_policy, enabled, version)
VALUES
    ('excel_extractor', 'Excel Extractor', 'Читает книги Excel, приложенные к задаче, и извлекает из них факты: даты ввода скважин (пары «скважина — дата»), параметры новых скважин (группа, интервал MD, диаметр, режим и дебит, BHP, VFP, траектория) и другие табличные данные. Сам выбирает лист и колонки; если таблица неоднозначна — спрашивает инженера. Не пишет SCHEDULE и не меняет файлы. Нужен хотя бы один приложенный Excel.', '["excel"]'::jsonb, '["facts","new_wells"]'::jsonb, '{"kind":"n8n_workflow","workflow_id":"3774c645-a20d-53df-9288-130173c400c2","workflow_name":"Agent — Excel Extractor"}'::jsonb, '{"artifacts":{"excel":"книга Excel инженера (одна или несколько)"},"handoff_message":"какие факты извлечь (даты ввода, параметры новых скважин, …)"}'::jsonb, '{"data":{"facts":"[{well, date}] — даты ввода скважин","new_wells":"[{well, group, …}] — параметры новых скважин"}}'::jsonb, 'agent_asks', true, '2'),
    ('calculation_agent', 'Calculation Agent', 'Если есть структурная поверхность и траектория скважины, находит их пересечение и начало интервала перфорации (глубина по стволу). Геометрия, не SCHEDULE.', '["surface","trajectory"]'::jsonb, '["top_perforation_md"]'::jsonb, '{"kind":"http","url":"{math_url}/agent/run"}'::jsonb, '{"artifacts":{"surface":"поверхность CPS3","trajectory":"траектория .dev"}}'::jsonb, '{"data":{"top_perforation_md":"глубина начала перфорации по стволу"}}'::jsonb, 'never', true, '2')
ON CONFLICT (agent_id) DO UPDATE SET title = EXCLUDED.title, when_to_use = EXCLUDED.when_to_use, input_required = EXCLUDED.input_required, output_provides = EXCLUDED.output_provides, invoke = EXCLUDED.invoke, input_schema = EXCLUDED.input_schema, output_schema = EXCLUDED.output_schema, hitl_policy = EXCLUDED.hitl_policy, enabled = EXCLUDED.enabled, version = EXCLUDED.version;
